<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/autokeras_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install autokeras

In [ ]:
!pip install colorama

In [ ]:
import numpy as np
import random
import os
import pickle
from colorama import Fore, Style
import time
import keras
from keras.models import load_model
from autokeras import StructuredDataClassifier


def output(matrix, x, y):
  for i in range(len(matrix)):
    for j in range(len(matrix[i])):
      if i == x and j == y:
        print(Fore.GREEN + str(int(matrix[i][j])) + Style.RESET_ALL, end=' ')
      else:
        print(str(int(matrix[i][j])), end=' ')
    print()

def obstacle(matrix, x, y, len):
  i = y
  while i < len + y:
    matrix[x][i] = 1
    i += 1
  return matrix

def map():
  field = np.zeros((16, 16))
  field = np.pad(field, pad_width=1, mode='constant', constant_values=1)
  obstacle(field,4,7,4)
  obstacle(field,5,6,6)
  obstacle(field,6,5,8)
  obstacle(field,7,4,10)
  obstacle(field,8,4,10)
  obstacle(field,9,4,10)
  obstacle(field,10,4,10)
  obstacle(field,11,5,8)
  obstacle(field,12,6,6)
  obstacle(field,13,7,4)
  return field

field = map()

def N(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
  return distance

def NE(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
    j += 1
  return distance

def E(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    j += 1
  return distance

def SE(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
    j += 1
  return distance

def S(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
  return distance

def SW(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
    j -= 1
  return distance

def W(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    j -= 1
  return distance

def NW(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
    j -= 1
  return distance

def radar(x, y):
  N_dist = N(x,y)
  NE_dist = NE(x,y)
  # E_dist = E(x,y)
  # SE_dist = SE(x,y)
  # S_dist = S(x,y)
  # SW_dist = SW(x,y)
  # W_dist = W(x,y)
  NW_dist = NW(x,y)
  return [N_dist, NE_dist, NW_dist]
  # return [N_dist, NE_dist, E_dist, SE_dist, S_dist, SW_dist, W_dist, NW_dist]

radar_array = []
button_array = []

def play(x, y):
  i = x
  j = y
  while True:
    button = input()
    os.system('clear')
    if button == "w":
      if field[i-1][j] == 1:
        field[i][j] = 2
        output(field, i, j)
        field[i][j] = 0
        continue
      field[i-1][j] = 2
      button_array.append([1,0,0])
      os.system('clear')
      output(field, i-1, j)
      field[i-1][j] = 0
      i -= 1
      radar_array.append(radar(i, j))
    elif button == "a":
      if field[i][j-1] == 1:
        field[i][j] = 2
        output(field, i, j)
        field[i][j] = 0
        continue
      field[i][j-1] = 2
      button_array.append([0,1,0])
      os.system('clear')
      output(field, i, j-1)
      field[i][j-1] = 0
      j -= 1
      radar_array.append(radar(i, j))
    elif button == "s":
      if field[i+1][j] == 1:
        field[i][j] = 2
        output(field, i, j)
        field[i][j] = 0
        continue
      field[i+1][j] = 2
      button_array.append([0,0,1])
      os.system('clear')
      output(field, i+1, j)
      field[i+1][j] = 0
      i += 1
      radar_array.append(radar(i, j))
    elif button == "d":
      if field[i][j+1] == 1:
        field[i][j] = 2
        output(field, i, j)
        field[i][j] = 0
        continue
      field[i][j+1] = 2
      button_array.append([0,0,0])
      os.system('clear')
      output(field, i, j+1)
      field[i][j+1] = 0
      j += 1
      radar_array.append(radar(i, j))
    elif button == "q":
      break
    else:
      output(field, i, j)

def random_start():
  flag = 1
  while flag:
    x = random.randint(15, 16)
    y = random.randint(7, 9)
    if x and y != 1:
      a = radar(x,y)
      if 0 not in a:
        print(f"Radar array {a}")
        field[x][y] = 2
        flag = 0
  return x, y

def start_point(x, y):
  field[x][y] = 2
  output(field, x, y)
  print("Move 2 around the tree and press \"q\"")
  print(f"Start point ({x}, {y})")
  print("Enter \"q\" to a new start")
  field[x][y] = 0
  play(x, y)
  os.system('clear')

def main():
  x, y = random_start()
  start_point(x, y)

main()

with open('radar_array.txt', 'ab') as out:
  pickle.dump(radar_array, out)
with open('button_array.txt', 'ab') as out:
  pickle.dump(button_array, out)

print(radar_array)
print(button_array)

In [64]:
with open('radar_array.txt', 'rb') as radar:
  X = pickle.load(radar)
X = np.array(X)
with open('button_array.txt', 'rb') as button:
  Y = pickle.load(button)
Y = np.array(Y)


X_train = np.array(X)
y_train = np.array(Y)


clf = StructuredDataClassifier(max_trials=16)   # для подбора гиперпараметров
clf.fit(X_train, y_train, epochs=20, verbose=0)     # для запоминания датасета


X_val = X_train
y_val = y_train
loss, accuracy = clf.evaluate(X_val, y_val)
print(loss, accuracy)


print(clf.predict(X_val[:20]))
print(y_val[:20])

model = clf.export_model()
model.summary()
model.save("model.keras")

Reloading Tuner from ./structured_data_classifier/tuner0.json
6/6 [==============================] - 0s 4ms/step - loss: 0.1780 - accuracy: 0.9341
0.17800605297088623 0.9340659379959106
1/1 [==============================] - 0s 6ms/step
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[[0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 3)]               0         
                                                                 
 multi_category_encoding (M  (None, 3)                 0      

In [ ]:
def output(matrix, x, y):
  for i in range(len(matrix)):
    for j in range(len(matrix[i])):
      if i == x and j == y:
        print(Fore.GREEN + str(int(matrix[i][j])) + Style.RESET_ALL, end=' ')
      else:
        print(str(int(matrix[i][j])), end=' ')
    print()

def obstacle(matrix, x, y, len):
  i = y
  while i < len + y:
    matrix[x][i] = 1
    i += 1
  return matrix

def map():
  field = np.zeros((16, 16))
  field = np.pad(field, pad_width=1, mode='constant', constant_values=1)
  obstacle(field,4,7,4)
  obstacle(field,5,6,6)
  obstacle(field,6,5,8)
  obstacle(field,7,4,10)
  obstacle(field,8,4,10)
  obstacle(field,9,4,10)
  obstacle(field,10,4,10)
  obstacle(field,11,5,8)
  obstacle(field,12,6,6)
  obstacle(field,13,7,4)
  return field

field = map()

def N(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
  return distance

def NE(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
    j += 1
  return distance

def E(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    j += 1
  return distance

def SE(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
    j += 1
  return distance

def S(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
  return distance

def SW(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i += 1
    j -= 1
  return distance

def W(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    j -= 1
  return distance

def NW(x,y):
  distance = 0
  i = x
  j = y
  while field[i][j] != 1:
    distance += 1
    i -= 1
    j -= 1
  return distance

def radar(x, y):
  N_dist = N(x,y)
  NE_dist = NE(x,y)
  # E_dist = E(x,y)
  # SE_dist = SE(x,y)
  # S_dist = S(x,y)
  # SW_dist = SW(x,y)
  # W_dist = W(x,y)
  NW_dist = NW(x,y)
  return [N_dist, NE_dist, NW_dist]
  # return [N_dist, NE_dist, E_dist, SE_dist, S_dist, SW_dist, W_dist, NW_dist]


model = load_model('model.keras')


def move(x,y):
  i = x
  j = y
  input = radar(i, j)
  test = np.array(input)
  prediction = model.predict(test)
  prediction = list(prediction)
  value = max(prediction)
  button = prediction.index(value)
  os.system('clear')
  print(f"Prediction: {button}")
  if button == 0:
    field[i-1][j] = 2
    output(field,i-1,j)
    field[i-1][j] = 0
    i -= 1
    time.sleep(1)
  if button == 1:
    field[i][j-1] = 2
    output(field,i,j-1)
    field[i][j-1] = 0
    j -= 1
    time.sleep(1)
  if button == 2:
    field[i+1][j] = 2
    output(field,i+1,j)
    field[i+1][j] = 0
    i += 1
    time.sleep(1)
  if button == 3:
    field[i][j+1] = 2
    output(field,i,j+1)
    field[i][j+1] = 0
    j += 1
    time.sleep(1)
  return i, j

def main():
  x, y = move(15, 8)
  for i in range(10):
    x, y = move(x, y)

main()