<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/CentralMomentsMethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np

matrix1 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
], dtype=np.float32)

matrix1[1:5, 1:5] = 1

matrix2 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
], dtype=np.float32)

matrix2[0:4, 0:4] = 1

print("Матрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)

# Вычисляем смещение по центрам масс
y1, x1 = np.where(matrix1 > 0)
y2, x2 = np.where(matrix2 > 0)

center_y1, center_x1 = np.mean(y1), np.mean(x1)
center_y2, center_x2 = np.mean(y2), np.mean(x2)

shift_x = center_x2 - center_x1
shift_y = center_y2 - center_y1

print(f"\nСмещение: x={shift_x:.1f}, y={shift_y:.1f}")

# Вычисляем угол поворота через моменты инерции
cy1, cx1 = np.mean(y1), np.mean(x1)
cy2, cx2 = np.mean(y2), np.mean(x2)

mu11_1 = np.mean((x1 - cx1) * (y1 - cy1))
mu20_1 = np.mean((x1 - cx1) ** 2)
mu02_1 = np.mean((y1 - cy1) ** 2)

mu11_2 = np.mean((x2 - cx2) * (y2 - cy2))
mu20_2 = np.mean((x2 - cx2) ** 2)
mu02_2 = np.mean((y2 - cy2) ** 2)

angle1 = 0.5 * np.arctan2(2 * mu11_1, mu20_1 - mu02_1)
angle2 = 0.5 * np.arctan2(2 * mu11_2, mu20_2 - mu02_2)

rotation = np.degrees(angle2 - angle1)

print(f"Угол поворота: {rotation:.1f}°")

Матрица 1:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Матрица 2:
[[1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Смещение: x=-1.0, y=-1.0
Угол поворота: 0.0°


In [17]:
import numpy as np

matrix1 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
], dtype=np.float32)

matrix2 = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
], dtype=np.float32)

print("Матрица 1:")
print(matrix1)
print("\nМатрица 2:")
print(matrix2)

# Вычисляем смещение по центрам масс
y1, x1 = np.where(matrix1 > 0)
y2, x2 = np.where(matrix2 > 0)

center_y1, center_x1 = np.mean(y1), np.mean(x1)
center_y2, center_x2 = np.mean(y2), np.mean(x2)

shift_x = center_x2 - center_x1
shift_y = center_y2 - center_y1

print(f"\nСмещение: x={shift_x:.1f}, y={shift_y:.1f}")

# Вычисляем угол поворота через моменты инерции
cy1, cx1 = np.mean(y1), np.mean(x1)
cy2, cx2 = np.mean(y2), np.mean(x2)

mu11_1 = np.mean((x1 - cx1) * (y1 - cy1))
mu20_1 = np.mean((x1 - cx1) ** 2)
mu02_1 = np.mean((y1 - cy1) ** 2)

mu11_2 = np.mean((x2 - cx2) * (y2 - cy2))
mu20_2 = np.mean((x2 - cx2) ** 2)
mu02_2 = np.mean((y2 - cy2) ** 2)

angle1 = 0.5 * np.arctan2(2 * mu11_1, mu20_1 - mu02_1)
angle2 = 0.5 * np.arctan2(2 * mu11_2, mu20_2 - mu02_2)

rotation = np.degrees(angle2 - angle1)

print(f"Угол поворота: {rotation:.1f}°")

Матрица 1:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Матрица 2:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Смещение: x=3.5, y=1.0
Угол поворота: -135.0°
