<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import numpy as np
from abc import ABC, abstractmethod

class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  @property
  def board(self):
    return self.__board

  @board.setter
  def board(self, board):
    self.__board = board

  def set_piece(self, x, y):
    self.__board[x][y] = 1

  def delete_piece(self, x, y):
    self.__board[x][y] = 0


class Piece:
  def __init__(self, name, x, y):
    self.__name = name
    self.__x = x
    self.__y = y

  @property
  def name(self):
    return self.__name

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


class Game:
  def __init__(self, list_pieces):
    self.__new_board = Board()
    self.__chess_pieces = list_pieces

  @property
  def board(self):
    return self.__new_board.board

  @board.setter
  def board(self, board):
    self.__new_board.board = board

  def start(self):
    for piece in self.__chess_pieces:
      self.__new_board.set_piece(piece.x, piece.y)

  def delete_start_piece(self, x, y):
    self.__new_board.delete_piece(x, y)

  def move(self, x_old, y_old, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece.x == x_old & piece.y == y_old:
        self.__new_board.delete_piece(piece.x, piece.y)
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new

class Player:
  def __init__(self, name, list_pieces):
    self.__name = name
    self.__game = Game(list_pieces)

  @property
  def game(self):
    return self.__game

  @game.setter
  def game(self, game):
    self.__game = game

  def start(self):
    self.__game.start()

  def delete_start_piece(self, x, y):
    self.__game.delete_start_piece(x, y)

  def move(self, x_old, y_old, x_new, y_new):
    self.__game.move(x_old, y_old, x_new, y_new)


class Play:
  def __init__(self, name1, name2, list_pieces):
    self.__player1 = Player(name1, list_pieces)
    self.__player2 = Player(name2, list_pieces)
    self.__color = True

  def __str__(self):
    if self.__color == True:
      return str(self.__player1.game.board)
    else:
      return str(self.__player2.game.board)

  @property
  def player1(self):
    return self.__player1

  def start(self):
    self.__player1.start()
    self.__player2.start()

  def rotate_board(self):
    if self.__color:
      board = self.__player1.game.board
      self.__player2.game.board = np.rot90(board, 2)
      self.__color = False
    else:
      board = self.__player2.game.board
      self.__player1.game.board = np.rot90(board, 2)
      self.__color = True

  def move_white_player(self, x_old, y_old, x_new, y_new):
    # horizontal = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5, 'g':6, 'h':7}
    # vertical = {'8':0, '7':1, '6':2, '5':3, '4':4, '3':5, '2':6, '1':7}
    # y_new = int(horizontal[x])
    # x_new = int(vertical[y])
    print(f'{x_old},{y_old},{x_new},{y_new}')
    self.__player1.move(x_old, y_old, x_new, y_new)

  # def move_black_player(self, x_old, y_old, x_new, y_new):
  #   # horizontal = {'h':0, 'g':1, 'f':2, 'e':3, 'd':4, 'c':5, 'b':6, 'a':7}
  #   # vertical = {'8':7, '7':6, '6':5, '5':4, '4':3, '3':2, '2':1, '1':0}
  #   # y_new = int(horizontal[x])
  #   # x_new = int(vertical[y])
  #   print(f'{x_old},{y_old},{x_new},{y_new}')
  #   self.__player2.move(x_old, y_old, x_new, y_new)


class ListPieces:
  def __init__(self):
    self.__white_king = Piece('white_king', 7, 4) # e1
    self.__black_king = Piece('black_king', 0, 4) # e8
    self.__start_chess_list = [self.__white_king, self.__black_king]

  @property
  def start_chess_list(self):
    return self.__start_chess_list


class Service:
  def __init__(self, name1, name2):
    self.name1 = name1
    self.name2 = name2
    self.list_pieces = ListPieces()
    self.play = Play(name1, name2, self.list_pieces.start_chess_list)

  def start(self):
    self.play.start()

  def print_board(self):
    print(self.play)

  def rotate_board(self):
    self.play.rotate_board()

  # def clear_first_black_move(self, x_old, y_old):
  #   for piece in self.list_pieces.start_chess_list:
  #     if piece.x == x_old & piece.y == y_old:
  #       self.play.player1.delete_start_piece(piece.x, piece.y)

  def white_move(self, x_old, y_old, x_new, y_new):
    print(f"Ход {self.name1}")
    self.play.move_white_player(x_old, y_old, x_new, y_new)

  def black_move(self, x_old, y_old, x_new, y_new):
    print(f"Ход {self.name2}")
    self.play.move_black_player(x_old, y_old, x_new, y_new)


class Presenter:
  def __init__(self):
    # self.name1 = input("Введите имя 1 игрока:\n")
    # self.name2 = input("Введите имя 2 игрока:\n")
    self.name1 = 'ann'
    self.name2 = 'mike'
    self.service = Service(self.name1, self.name2)

  def start(self):
    self.service.start()

  def print_board(self):
    self.service.print_board()

  def rotate_board(self):
    self.service.rotate_board()

  def white_move(self):
    item = input("Введите ход:\n")
    old_horizontal = item[0]
    old_vertical = item[1]
    new_horizontal = item[2]
    new_vertical = item[3]
    horizontal = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5, 'g':6, 'h':7}
    vertical = {'8':0, '7':1, '6':2, '5':3, '4':4, '3':5, '2':6, '1':7}
    y_old = int(horizontal[old_horizontal])
    x_old = int(vertical[old_vertical])
    y_new = int(horizontal[new_horizontal])
    x_new = int(vertical[new_vertical])
    print(x_old, y_old, x_new, y_new)
    self.service.white_move(x_old, y_old, x_new, y_new)

  def black_move(self):
    item = input("Введите ход:\n")
    old_horizontal = item[0]
    old_vertical = item[1]
    new_horizontal = item[2]
    new_vertical = item[3]
    horizontal = {'h':0, 'g':1, 'f':2, 'e':3, 'd':4, 'c':5, 'b':6, 'a':7}
    vertical = {'8':7, '7':6, '6':5, '5':4, '4':3, '3':2, '2':1, '1':0}
    y_old = int(horizontal[old_horizontal])
    x_old = int(vertical[old_vertical])
    y_new = int(horizontal[new_horizontal])
    x_new = int(vertical[new_vertical])
    print(x_old, y_old, x_new, y_new)
    self.service.black_move(x_old, y_old, x_new, y_new)
    # self.service.clear_first_black_move(x_old, y_old)


class View:
  def __init__(self):
    self.presenter = Presenter()
    self.work = True

  def start_new_game(self):
    self.move_counter = 0
    self.presenter.print_board()
    self.presenter.start()
    self.presenter.print_board()
    self.presenter.white_move()
    self.presenter.print_board()


  def finish(self):
    print("Выход")
    self.work = False


def main():
  v = View()
  v.start_new_game()

main()

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
Введите ход:
e1e2
7 4 6 4
Ход ann
7,4,6,4
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
