<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

class Board:
  def __init__(self):
    self.board = np.zeros((8,8))

  def __str__(self):
    return str(self.board)

  def put_figure(self, x, y):
    self.board[x][y] = 1

  def rotate(self):
    self.board = np.rot90(self.board, 2)


class Figure:
  def __init__(self, x, y):
    self.__x = x
    self.__y = y

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


class Game:
  def __init__(self):
    self.board = Board()
    self.figures = [Figure(2,2), Figure(3,3)]

  def print_board(self):
    print(self.board)

  def start(self):
    for f in self.figures:
      self.board.put_figure(f.x, f.y)

  def rotate(self):
    self.board.rotate()





game = Game()
game.start()
game.print_board()
game.rotate()
game.print_board()

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
