<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

class Board:
  def __init__(self, rotation: int, x_old: int, y_old: int):
    self.board = np.zeros((8,8))
    self.rotation = rotation
    self.x_old = x_old
    self.y_old = y_old

  def __str__(self):
    return str(self.board)

# x_new: int, y_new: int
  def move(self):
    self.board[2][1] = 1


b = Board(0, 0, 0)
b.move()
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
