<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import copy

class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  @property
  def board(self):
    return self.__board

  @board.setter
  def board(self, board):
    self.__board = board

  def set_piece(self, x, y):
    self.__board[x][y] = 1

  def delete_piece(self, x, y):
    self.__board[x][y] = 0



class Piece:
  def __init__(self, x, y):
    self.__x = x
    self.__y = y

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


white_king = Piece(1, 1)
black_king = Piece(3, 3)

class Game:
  def __init__(self):
    self.__new_board = Board()
    self.__chess_pieces = [white_king, black_king]

  @property
  def board(self):
    return self.__new_board.board

  @board.setter
  def board(self, board):
    self.__new_board.board = board

  def start(self):
    for piece in self.__chess_pieces:
      self.__new_board.set_piece(piece.x, piece.y)

  def move(self, item, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece == item:
        self.__new_board.delete_piece(piece.x, piece.y)
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new


class Player:
  def __init__(self, name, color):
    self.__name = name
    self.__color = color
    self.__game = Game()

  @property
  def game(self):
    return self.__game

  @game.setter
  def game(self, game):
    self.__game = game

  def start(self):
    self.__game.start()

  def move(self, item, x_new, y_new):
    self.__game.move(item, x_new, y_new)



class Play:
  def __init__(self):
    self.__player1 = Player('alex', 0)
    self.__player2 = Player('ann', 1)
    self.__color = True

  def __str__(self):
    if self.__color == True:
      return str(self.__player1.game.board)
    else:
      return str(self.__player2.game.board)

  def start(self):
    self.__player1.start()
    self.__player2.start()


  def move_white_player(self, item, x_new, y_new):
    self.__player1.move(item, x_new, y_new)
    self.color = False

  def move_black_player(self, item, x_new, y_new):
    self.__player2.move(item, x_new, y_new)
    self.__color = True

  def rotate_board(self):
    if self.__color:
      board = self.__player1.game.board
      self.__player2.game.board = copy.deepcopy(np.rot90(board, 2))
      del(board)
      self.__color = False
    else:
      board = self.__player2.game.board
      self.__player1.game.board = copy.deepcopy(np.rot90(board, 2))
      del(board)
      self.__color = True



p = Play()
print(p)
p.start()
print(p)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
