<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [284]:
import numpy as np


class Piece:
  def __init__(self, color, x, y):
    self.__color = color
    self.__x = x
    self.__y = y

  @property
  def color(self):
    return self.__color

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


white_king = Piece('white', 'e', '1') # e1
black_king = Piece('black', 'e', '8') # e8

class Board:
  def __init__(self):
    self.board = np.zeros((8,8))
    self.start_chess_list = [white_king, black_king]

  def start(self):
    horizontal = {'a':'0', 'b':'1', 'c':'2', 'd':'3', 'e':'4', 'f':'5', 'g':'6', 'h':'7'}
    vertical = {'8':'0', '7':'1', '6':'2', '5':'3', '4':'4', '3':'5', '2':'6', '1':'7'}
    for piece in self.start_chess_list:
      y = int(horizontal[piece.x])
      x = int(vertical[piece.y])
      self.board[x][y] = 1

  def move(self, color, x_old, y_old, x_new, y_new):
    if color == 'white':
      x_change = x_old
      y_change = y_old
      horizontal = {'a':'0', 'b':'1', 'c':'2', 'd':'3', 'e':'4', 'f':'5', 'g':'6', 'h':'7'}
      vertical = {'8':'0', '7':'1', '6':'2', '5':'3', '4':'4', '3':'5', '2':'6', '1':'7'}
      x_old = int(horizontal[x_old])
      y_old = int(vertical[y_old])
      x_new = int(horizontal[x_new])
      y_new = int(vertical[y_new])
      for piece in self.start_chess_list:
        piece.x = x_change
        piece.y = y_change
        x = int(horizontal[piece.x])
        y = int(vertical[piece.y])
        if x == x_old and y == y_old:
          self.board[y_new][x_new] = 1
          self.board[y_old][x_old] = 0
    elif color == 'black':
      x_change = x_old
      y_change = y_old
      horizontal = {'h':'0', 'g':'1', 'f':'2', 'e':'3', 'd':'4', 'c':'5', 'b':'6', 'a':'7'}
      vertical = {'8':'7', '7':'6', '6':'5', '5':'4', '4':'3', '3':'2', '2':'1,', '1':'0'}
      x_old = int(horizontal[x_old])
      y_old = int(vertical[y_old])
      x_new = int(horizontal[x_new])
      y_new = int(vertical[y_new])
      for piece in self.start_chess_list:
        piece.x = x_change
        piece.y = y_change
        x = int(horizontal[piece.x])
        y = int(vertical[piece.y])
        if x == x_old and y == y_old:
          self.board[y_new][x_new] = 1
          self.board[y_old][x_old] = 0

  def rotate_board(self):
    self.board = np.rot90(self.board, 2)


class Player:
  def __init__(self, name, color):
    self.__name = name
    self.__color = color

  @property
  def name(self):
    return self.__name

  @name.setter
  def name(self, name):
    self.__name = name

  @property
  def color(self):
    return self.__color

  @color.setter
  def color(self, color):
    self.__color = color


class Service:
  def __init__(self):
    self.player1 = Player('ann', 'white')
    self.player2 = Player('mike', 'black')
    self.board = Board()

  def __str__(self):
    return str(self.board.board)

  def start(self):
    self.board.start()

  def white_move(self):
    item = input("Введите ход:\n")
    old_horizontal = item[0]
    old_vertical = item[1]
    new_horizontal = item[2]
    new_vertical = item[3]
    self.board.move(self.player1.color, old_horizontal, old_vertical, new_horizontal, new_vertical)

  def black_move(self):
    item = input("Введите ход:\n")
    old_horizontal = item[0]
    old_vertical = item[1]
    new_horizontal = item[2]
    new_vertical = item[3]
    self.board.move(self.player2.color, old_horizontal, old_vertical, new_horizontal, new_vertical)

  def rotate(self):
    self.board.rotate_board()


class View:
  def __init__(self):
    self.service = Service()

  def start(self):
    self.service.start()
    while True:
      print(self.service)
      print('---------------------------')
      self.service.white_move()
      print(self.service)
      print('---------------------------')
      self.service.rotate()
      print(self.service)
      print('---------------------------')
      self.service.black_move()
      print(self.service)
      print('---------------------------')
      self.service.rotate()


v = View()
v.start()

[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
---------------------------
Введите ход:
e1e7
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
---------------------------
Введите ход:
e1e2


ValueError: ignored