<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [179]:
import numpy as np

class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  def __str__(self):
    return f'{self.__board}'

  def rotate(self):
    self.__board = np.rot90(self.__board, 2)

  def set_piece(self, x, y):
    self.__board[x][y] = 1

  def delete_piece(self, x, y):
    self.__board[x][y] = 0



class Piece:
  def __init__(self, x, y):
    self.__x = x
    self.__y = y

  def __str__(self):
    return f'x = {self.__x}, y = {self.__y}'

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


king = Piece(0, 0)


class Game:
  def __init__(self):
    self.__new_board = Board()
    self.__chess_pieces = [king]

  def __str__(self):
    return str(self.__new_board)

  def rotate(self):
    self.__new_board.rotate()

  def move(self, item, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece == item:
        # self.__new_board.delete_piece(piece.x, piece.y)
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new


# copy matrix


game = Game()
game.move(king, 0, 0)
game.rotate()
print(game)
print('----------------------------')
game.move(king, 1, 1)
game.rotate()
print(game)
print('----------------------------')
game.move(king, 2, 2)
game.rotate()
print(game)
print('----------------------------')
game.move(king, 3, 3)
game.rotate()
print(game)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
----------------------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
----------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
----------------------------
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
