<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np


class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  @property
  def board(self):
    return self.__board

  @board.setter
  def board(self, board):
    self.__board = board

  def set_piece(self, x, y):
    self.__board[x][y] = 1

  def delete_piece(self, x, y):
    self.__board[x][y] = 0


class Piece:
  def __init__(self, name, x, y):
    self.__name = name
    self.__x = x
    self.__y = y

  @property
  def name(self):
    return self.__name

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


class Game:
  def __init__(self, list_pieces):
    self.__new_board = Board()
    self.__chess_pieces = list_pieces

  @property
  def board(self):
    return self.__new_board.board

  @board.setter
  def board(self, board):
    self.__new_board.board = board

  def start(self):
    for piece in self.__chess_pieces:
      self.__new_board.set_piece(piece.x, piece.y)

  def delete_start_piece(self, x, y):
    self.__new_board.delete_piece(x, y)

  def move(self, item, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece.name == item:
        self.__new_board.delete_piece(piece.x, piece.y)
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new

class Player:
  def __init__(self, name, color, list_pieces):
    self.__name = name
    self.__color = color
    self.__game = Game(list_pieces)

  @property
  def game(self):
    return self.__game

  @game.setter
  def game(self, game):
    self.__game = game

  def start(self):
    self.__game.start()

  def delete_start_piece(self, x, y):
    self.__game.delete_start_piece(x, y)

  def move(self, item, x_new, y_new):
    self.__game.move(item, x_new, y_new)


class Play:
  def __init__(self, list_pieces):
    self.__player1 = Player('alex', 0, list_pieces)
    self.__player2 = Player('ann', 1, list_pieces)
    self.__color = True

  def __str__(self):
    if self.__color == True:
      return str(self.__player1.game.board)
    else:
      return str(self.__player2.game.board)

  @property
  def player1(self):
    return self.__player1

  def start(self):
    self.__player1.start()
    self.__player2.start()

  def rotate_board(self):
    if self.__color:
      board = self.__player1.game.board
      self.__player2.game.board = np.rot90(board, 2)
      self.__color = False
    else:
      board = self.__player2.game.board
      self.__player1.game.board = np.rot90(board, 2)
      self.__color = True

  def move_white_player(self, item, x, y):
    horizontal = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5, 'g':6, 'h':7}
    vertical = {'8':0, '7':1, '6':2, '5':3, '4':4, '3':5, '2':6, '1':7}
    y_new = int(horizontal[x])
    x_new = int(vertical[y])
    print(f'{x}{y}')
    self.__player1.move(item, x_new, y_new)

  def move_black_player(self, item, x, y):
    horizontal = {'h':0, 'g':1, 'f':2, 'e':3, 'd':4, 'c':5, 'b':6, 'a':7}
    vertical = {'8':7, '7':6, '6':5, '5':4, '4':3, '3':2, '2':1, '1':0}
    y_new = int(horizontal[x])
    x_new = int(vertical[y])
    print(f'{x}{y}')
    self.__player2.move(item, x_new, y_new)


class ListPieces:
  def __init__(self):
    self.__white_king = Piece('white_king', 7, 4) # e1
    self.__black_king = Piece('black_king', 0, 4) # e8
    self.__start_chess_list = [self.__white_king, self.__black_king]

  @property
  def start_chess_list(self):
    return self.__start_chess_list


class Service:
  def __init__(self):
    self.list_pieces = ListPieces()
    self.play = Play(self.list_pieces.start_chess_list)

  def start(self):
    self.play.start()

  def print_board(self):
    print(self.play)

  def rotate_board(self):
    self.play.rotate_board()

  def clear_first_black_move(self, item):
    for p in self.list_pieces.start_chess_list:
      if p.name == item:
        self.play.player1.delete_start_piece(p.x, p.y)

  def white_move(self, item, x, y):
    self.play.move_white_player(item, x, y)

  def black_move(self, item, x, y):
    self.play.move_black_player(item, x, y)



s = Service()
s.start()
s.print_board()
print('---------------------------')
s.white_move('white_king', 'e', '2')
s.print_board()
print('---------------------------')
s.rotate_board()
s.print_board()
print('---------------------------')
s.clear_first_black_move('black_king')
s.black_move('black_king', 'e', '7')
s.print_board()

[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
---------------------------
e2
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
---------------------------
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
---------------------------
e7
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
