<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/chess.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
import numpy as np
import copy

class Board:
  def __init__(self):
    self.__board = np.zeros((8,8))

  @property
  def board(self):
    return self.__board

  @board.setter
  def board(self, board):
    self.__board = board

  def set_piece(self, x, y):
    self.__board[x][y] = 1


class Piece:
  def __init__(self, x, y):
    self.__x = x
    self.__y = y

  @property
  def x(self):
    return self.__x

  @x.setter
  def x(self, x):
    self.__x = x

  @property
  def y(self):
    return self.__y

  @y.setter
  def y(self, y):
    self.__y = y


white_king = Piece(7, 4)
black_king = Piece(0, 4)

class Game:
  def __init__(self):
    self.__new_board = Board()
    self.__chess_pieces = [white_king, black_king]

  @property
  def board(self):
    return self.__new_board.board

  @board.setter
  def board(self, board):
    self.__new_board.board = board

  def start(self):
    for piece in self.__chess_pieces:
      self.__new_board.set_piece(piece.x, piece.y)

  def move(self, item, x_new, y_new):
    for piece in self.__chess_pieces:
      if piece == item:
        self.__new_board.set_piece(x_new, y_new)
        piece.x = x_new
        piece.y = y_new


class Player:
  def __init__(self, name, color):
    self.__name = name
    self.__color = color
    self.__game = Game()

  @property
  def game(self):
    return self.__game

  @game.setter
  def game(self, game):
    self.__game = game

  def start(self):
    self.__game.start()

  def move(self, item, x_new, y_new):
    self.__game.move(item, x_new, y_new)



class Play:
  def __init__(self):
    self.__player1 = Player('alex', 0)
    self.__player2 = Player('ann', 1)
    self.__color = True

  def __str__(self):
    if self.__color == True:
      return str(self.__player1.game.board)
    else:
      return str(self.__player2.game.board)

  def start(self):
    self.__player1.start()
    self.__player2.start()


  def move_white_player(self, item, x, y):
    horizontal = {'a':0, 'b':1, 'c':2, 'd':3, 'e':4, 'f':5, 'g':6, 'h':7}
    vertical = {'8':0, '7':1, '6':2, '5':3, '4':4, '3':5, '2':6, '1':7}
    y_new = int(horizontal[x])
    x_new = int(vertical[y])
    print(f'{x}{y}')
    self.__player1.move(item, x_new, y_new)

  def move_black_player(self, item, x, y):
    horizontal = {'h':0, 'g':1, 'f':2, 'e':3, 'd':4, 'c':5, 'b':6, 'a':7}
    vertical = {'8':7, '7':6, '6':5, '5':4, '4':3, '3':2, '2':1, '1':0}
    y_new = int(horizontal[x])
    x_new = int(vertical[y])
    print(f'{x}{y}')
    self.__player2.move(item, x_new, y_new)

  def rotate_board(self):
    if self.__color:
      board = self.__player1.game.board
      self.__player2.game.board = copy.deepcopy(np.rot90(board, 2))
      del(board)
      self.__color = False
    else:
      board = self.__player2.game.board
      self.__player1.game.board = copy.deepcopy(np.rot90(board, 2))
      del(board)
      self.__color = True



p = Play()
p.start()
p.move_white_player(white_king, 'e', '2')
print(p)
print('---------------------------')
p.rotate_board()
p.move_black_player(black_king, 'e', '7')
print(p)
print('---------------------------')
p.rotate_board()
p.move_white_player(white_king, 'e', '3')
print(p)
print('---------------------------')
p.rotate_board()
p.move_black_player(black_king, 'e', '6')
print(p)
print('---------------------------')

e2
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
---------------------------
e7
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
---------------------------
e3
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]]
---------------------------
e6
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
---------------------------
