<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/L2_lambda_polynomial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import numpy as np
import random

X_train = np.array([
    [0.5, 0.2, 0.1, 0.0], [0.6, 0.3, 0.2, 0.1], [0.4, 0.1, 0.1, 0.0],
    [0.7, 0.4, 0.6, 0.3], [0.8, 0.5, 0.5, 0.4], [0.6, 0.3, 0.4, 0.2],
    [0.3, 0.8, 0.7, 0.9], [0.4, 0.9, 0.8, 0.8], [0.2, 0.7, 0.6, 0.7],
    [0.5, 0.6, 0.5, 0.6]
])
y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

weights = [random.uniform(-1, 1) for _ in range(16)]

learning_rate = 0.01
epochs = 5000
lambda_l2 = 0.01  # Коэффициент L2-регуляризации

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода"""
    x1, x2, x3, x4 = x
    return (
        coeffs[0] +  # константа
        coeffs[1]*x1 + coeffs[2]*x2 + coeffs[3]*x3 + coeffs[4]*x4 +
        coeffs[5]*x1*x2 + coeffs[6]*x1*x3 + coeffs[7]*x1*x4 +
        coeffs[8]*x2*x3 + coeffs[9]*x2*x4 + coeffs[10]*x3*x4 +
        coeffs[11]*x1*x2*x3 + coeffs[12]*x1*x2*x4 +
        coeffs[13]*x1*x3*x4 + coeffs[14]*x2*x3*x4 +
        coeffs[15]*x1*x2*x3*x4
    )

# Обучение с L2-регуляризацией
for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients = [
            1,                  # для w0 (константа)
            x1,                 # для w1
            x2,                 # для w2
            x3,                 # для w3
            x4,                 # для w4
            x1*x2,              # для w5
            x1*x3,              # для w6
            x1*x4,              # для w7
            x2*x3,              # для w8
            x2*x4,              # для w9
            x3*x4,              # для w10
            x1*x2*x3,           # для w11
            x1*x2*x4,           # для w12
            x1*x3*x4,           # для w13
            x2*x3*x4,           # для w14
            x1*x2*x3*x4         # для w15
        ]

        # Обновление весов с L2-регуляризацией (кроме константы w0)
        for k in range(16):
            if k == 0:
                # Для константы регуляризация не применяется
                weights[k] -= learning_rate * error * gradients[k]
            else:
                weights[k] -= learning_rate * (error * gradients[k] + lambda_l2 * weights[k])

    if epoch % 500 == 0:
        # Добавляем L2-штраф к общей ошибке для вывода
        l2_penalty = 0.5 * lambda_l2 * sum(w**2 for w in weights[1:])
        print(f"Эпоха {epoch}, Ошибка: {total_error:.6f}, L2-штраф: {l2_penalty:.6f}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x} -> {pred:.4f} ({y_train[i]})")

# Вывод уравнения
print(f"\nУравнение с L2-регуляризацией (λ={lambda_l2}):")
print(f"y = {weights[0]:.4f} + {weights[1]:.4f}*x1 + {weights[2]:.4f}*x2 + {weights[3]:.4f}*x3 + {weights[4]:.4f}*x4 +")
print(f"    {weights[5]:.4f}*x1*x2 + {weights[6]:.4f}*x1*x3 + {weights[7]:.4f}*x1*x4 + {weights[8]:.4f}*x2*x3 + {weights[9]:.4f}*x2*x4 + {weights[10]:.4f}*x3*x4 +")
print(f"    {weights[11]:.4f}*x1*x2*x3 + {weights[12]:.4f}*x1*x2*x4 + {weights[13]:.4f}*x1*x3*x4 + {weights[14]:.4f}*x2*x3*x4 +")
print(f"    {weights[15]:.4f}*x1*x2*x3*x4")

Эпоха 0, Ошибка: 15.022359, L2-штраф: 0.030960
Эпоха 500, Ошибка: 0.688112, L2-штраф: 0.018627
Эпоха 1000, Ошибка: 0.630692, L2-штраф: 0.015875
Эпоха 1500, Ошибка: 0.605926, L2-штраф: 0.015182
Эпоха 2000, Ошибка: 0.594598, L2-штраф: 0.015061
Эпоха 2500, Ошибка: 0.589191, L2-штраф: 0.015082
Эпоха 3000, Ошибка: 0.586512, L2-штраф: 0.015124
Эпоха 3500, Ошибка: 0.585139, L2-штраф: 0.015159
Эпоха 4000, Ошибка: 0.584412, L2-штраф: 0.015183
Эпоха 4500, Ошибка: 0.584017, L2-штраф: 0.015198

Результаты:
Вход -> Предсказание (Истинное значение)
[0.5 0.2 0.1 0. ] -> 0.0937 (0)
[0.6 0.3 0.2 0.1] -> 0.3422 (0)
[0.4 0.1 0.1 0. ] -> 0.0937 (0)
[0.7 0.4 0.6 0.3] -> 1.0449 (1)
[0.8 0.5 0.5 0.4] -> 1.1384 (1)
[0.6 0.3 0.4 0.2] -> 0.6828 (1)
[0.3 0.8 0.7 0.9] -> 2.1917 (2)
[0.4 0.9 0.8 0.8] -> 2.1618 (2)
[0.2 0.7 0.6 0.7] -> 1.8123 (2)
[0.5 0.6 0.5 0.6] -> 1.5366 (2)

Уравнение с L2-регуляризацией (λ=0.01):
y = 0.1522 + -0.4841*x1 + 0.4644*x2 + 0.7962*x3 + 1.2116*x4 +
    -0.0007*x1*x2 + 0.2352*x1*x3 + 0

In [104]:
import numpy as np
import random

X_train = np.array([
    [0.5, 0.2, 0.1, 0.0], [0.6, 0.3, 0.2, 0.1], [0.4, 0.1, 0.1, 0.0],
    [0.7, 0.4, 0.6, 0.3], [0.8, 0.5, 0.5, 0.4], [0.6, 0.3, 0.4, 0.2],
    [0.3, 0.8, 0.7, 0.9], [0.4, 0.9, 0.8, 0.8], [0.2, 0.7, 0.6, 0.7],
    [0.5, 0.6, 0.5, 0.6]
])
y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

weights = [random.uniform(-1, 1) for _ in range(16)]

learning_rate = 0.01
epochs = 5000

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода"""
    x1, x2, x3, x4 = x
    return (
        coeffs[0] +  # константа
        coeffs[1]*x1 + coeffs[2]*x2 + coeffs[3]*x3 + coeffs[4]*x4 +
        coeffs[5]*x1*x2 + coeffs[6]*x1*x3 + coeffs[7]*x1*x4 +
        coeffs[8]*x2*x3 + coeffs[9]*x2*x4 + coeffs[10]*x3*x4 +
        coeffs[11]*x1*x2*x3 + coeffs[12]*x1*x2*x4 +
        coeffs[13]*x1*x3*x4 + coeffs[14]*x2*x3*x4 +
        coeffs[15]*x1*x2*x3*x4
    )

# Обучение с L2-регуляризацией
for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients = [
            1,                  # для w0 (константа)
            x1,                 # для w1
            x2,                 # для w2
            x3,                 # для w3
            x4,                 # для w4
            x1*x2,              # для w5
            x1*x3,              # для w6
            x1*x4,              # для w7
            x2*x3,              # для w8
            x2*x4,              # для w9
            x3*x4,              # для w10
            x1*x2*x3,           # для w11
            x1*x2*x4,           # для w12
            x1*x3*x4,           # для w13
            x2*x3*x4,           # для w14
            x1*x2*x3*x4         # для w15
        ]

        for k in range(len(weights)):
            weights[k] -= learning_rate * error * gradients[k]

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error:.6f}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x} -> {pred:.4f} ({y_train[i]})")

# Вывод уравнения
print(f"\nУравнение (без регуляризации):")
print(f"y = {weights[0]:.4f} + {weights[1]:.4f}*x1 + {weights[2]:.4f}*x2 + {weights[3]:.4f}*x3 + {weights[4]:.4f}*x4 +")
print(f"    {weights[5]:.4f}*x1*x2 + {weights[6]:.4f}*x1*x3 + {weights[7]:.4f}*x1*x4 + {weights[8]:.4f}*x2*x3 + {weights[9]:.4f}*x2*x4 + {weights[10]:.4f}*x3*x4 +")
print(f"    {weights[11]:.4f}*x1*x2*x3 + {weights[12]:.4f}*x1*x2*x4 + {weights[13]:.4f}*x1*x3*x4 + {weights[14]:.4f}*x2*x3*x4 +")
print(f"    {weights[15]:.4f}*x1*x2*x3*x4")

Эпоха 0, Ошибка: 13.373862
Эпоха 500, Ошибка: 0.646148
Эпоха 1000, Ошибка: 0.468413
Эпоха 1500, Ошибка: 0.374649
Эпоха 2000, Ошибка: 0.322756
Эпоха 2500, Ошибка: 0.292208
Эпоха 3000, Ошибка: 0.272776
Эпоха 3500, Ошибка: 0.259317
Эпоха 4000, Ошибка: 0.249214
Эпоха 4500, Ошибка: 0.241110

Результаты:
Вход -> Предсказание (Истинное значение)
[0.5 0.2 0.1 0. ] -> -0.0770 (0)
[0.6 0.3 0.2 0.1] -> 0.2159 (0)
[0.4 0.1 0.1 0. ] -> 0.0286 (0)
[0.7 0.4 0.6 0.3] -> 1.1208 (1)
[0.8 0.5 0.5 0.4] -> 1.1210 (1)
[0.6 0.3 0.4 0.2] -> 0.7305 (1)
[0.3 0.8 0.7 0.9] -> 2.1181 (2)
[0.4 0.9 0.8 0.8] -> 1.9339 (2)
[0.2 0.7 0.6 0.7] -> 2.0712 (2)
[0.5 0.6 0.5 0.6] -> 1.7754 (2)

Уравнение (без регуляризации):
y = 0.6373 + -2.1953*x1 + 0.9369*x2 + 1.3719*x3 + 1.9772*x4 +
    0.3260*x1*x2 + 0.8533*x1*x3 + 1.0545*x1*x4 + -1.0135*x2*x3 + -0.7118*x2*x4 + -0.3090*x3*x4 +
    0.3784*x1*x2*x3 + 0.4127*x1*x2*x4 + -0.6866*x1*x3*x4 + -1.4996*x2*x3*x4 +
    0.7640*x1*x2*x3*x4


In [107]:
import numpy as np
import random

X_train = np.array([
    [0.5, 0.2, 0.1, 0.0], [0.6, 0.3, 0.2, 0.1], [0.4, 0.1, 0.1, 0.0],
    [0.7, 0.4, 0.6, 0.3], [0.8, 0.5, 0.5, 0.4], [0.6, 0.3, 0.4, 0.2],
    [0.3, 0.8, 0.7, 0.9], [0.4, 0.9, 0.8, 0.8], [0.2, 0.7, 0.6, 0.7],
    [0.5, 0.6, 0.5, 0.6]
])

y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

weights = [random.uniform(-1, 1) for _ in range(20)]

learning_rate = 0.01
epochs = 5000
lambda_l2 = 0.01

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода"""
    x1, x2, x3, x4 = x
    return (
        coeffs[0] +  # константа
        coeffs[1]*x1 + coeffs[2]*x2 + coeffs[3]*x3 + coeffs[4]*x4 +
        coeffs[5]*x1**2 + coeffs[6]*x2**2 + coeffs[7]*x3**2 + coeffs[8]*x4**2 +
        coeffs[9]*x1*x2 + coeffs[10]*x1*x3 + coeffs[11]*x1*x4 +
        coeffs[12]*x2*x3 + coeffs[13]*x2*x4 + coeffs[14]*x3*x4 +
        coeffs[15]*x1*x2*x3 + coeffs[16]*x1*x2*x4 +
        coeffs[17]*x1*x3*x4 + coeffs[18]*x2*x3*x4 +
        coeffs[19]*x1*x2*x3*x4
    )

# Обучение с L2-регуляризацией
for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients = [
            1,                  # w0 (константа)
            x1,                 # w1
            x2,                 # w2
            x3,                 # w3
            x4,                 # w4
            x1**2,              # w5 (x1^2)
            x2**2,              # w6 (x2^2)
            x3**2,              # w7 (x3^2)
            x4**2,              # w8 (x4^2)
            x1*x2,              # w9
            x1*x3,              # w10
            x1*x4,              # w11
            x2*x3,              # w12
            x2*x4,              # w13
            x3*x4,              # w14
            x1*x2*x3,           # w15
            x1*x2*x4,           # w16
            x1*x3*x4,           # w17
            x2*x3*x4,           # w18
            x1*x2*x3*x4         # w19
        ]

        # Обновление весов с L2-регуляризацией
        for k in range(len(weights)):
            if k == 0:
                weights[k] -= learning_rate * error * gradients[k]
            else:
                weights[k] -= learning_rate * (error * gradients[k] + lambda_l2 * weights[k])

    if epoch % 500 == 0:
        l2_penalty = 0.5 * lambda_l2 * sum(w**2 for w in weights[1:])
        print(f"Эпоха {epoch}, Ошибка: {total_error:.6f}, L2-штраф: {l2_penalty:.6f}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x} -> {pred:.4f} ({y_train[i]})")

# Вывод уравнения
print(f"\nУравнение с квадратными членами и L2-регуляризацией (λ={lambda_l2}):")
print(f"y = {weights[0]:.4f} + {weights[1]:.4f}*x1 + {weights[2]:.4f}*x2 + {weights[3]:.4f}*x3 + {weights[4]:.4f}*x4 +")
print(f"    {weights[5]:.4f}*x1^2 + {weights[6]:.4f}*x2^2 + {weights[7]:.4f}*x3^2 + {weights[8]:.4f}*x4^2 +")
print(f"    {weights[9]:.4f}*x1*x2 + {weights[10]:.4f}*x1*x3 + {weights[11]:.4f}*x1*x4 + {weights[12]:.4f}*x2*x3 + {weights[13]:.4f}*x2*x4 + {weights[14]:.4f}*x3*x4 +")
print(f"    {weights[15]:.4f}*x1*x2*x3 + {weights[16]:.4f}*x1*x2*x4 + {weights[17]:.4f}*x1*x3*x4 + {weights[18]:.4f}*x2*x3*x4 +")
print(f"    {weights[19]:.4f}*x1*x2*x3*x4")

Эпоха 0, Ошибка: 36.937425, L2-штраф: 0.029532
Эпоха 500, Ошибка: 0.699046, L2-штраф: 0.019526
Эпоха 1000, Ошибка: 0.617836, L2-штраф: 0.016168
Эпоха 1500, Ошибка: 0.584928, L2-штраф: 0.015438
Эпоха 2000, Ошибка: 0.570550, L2-штраф: 0.015356
Эпоха 2500, Ошибка: 0.563992, L2-штраф: 0.015404
Эпоха 3000, Ошибка: 0.560919, L2-штраф: 0.015459
Эпоха 3500, Ошибка: 0.559452, L2-штраф: 0.015496
Эпоха 4000, Ошибка: 0.558744, L2-штраф: 0.015519
Эпоха 4500, Ошибка: 0.558399, L2-штраф: 0.015531

Результаты:
Вход -> Предсказание (Истинное значение)
[0.5 0.2 0.1 0. ] -> 0.0967 (0)
[0.6 0.3 0.2 0.1] -> 0.3309 (0)
[0.4 0.1 0.1 0. ] -> 0.1094 (0)
[0.7 0.4 0.6 0.3] -> 1.0465 (1)
[0.8 0.5 0.5 0.4] -> 1.1015 (1)
[0.6 0.3 0.4 0.2] -> 0.6872 (1)
[0.3 0.8 0.7 0.9] -> 2.2022 (2)
[0.4 0.9 0.8 0.8] -> 2.1651 (2)
[0.2 0.7 0.6 0.7] -> 1.8127 (2)
[0.5 0.6 0.5 0.6] -> 1.5550 (2)

Уравнение с квадратными членами и L2-регуляризацией (λ=0.01):
y = 0.1574 + -0.3396*x1 + 0.4651*x2 + 0.8093*x3 + 1.1755*x4 +
    -0.3436*x1

In [106]:
import numpy as np
import random

X_train = np.array([
    [0.5, 0.2, 0.1, 0.0], [0.6, 0.3, 0.2, 0.1], [0.4, 0.1, 0.1, 0.0],
    [0.7, 0.4, 0.6, 0.3], [0.8, 0.5, 0.5, 0.4], [0.6, 0.3, 0.4, 0.2],
    [0.3, 0.8, 0.7, 0.9], [0.4, 0.9, 0.8, 0.8], [0.2, 0.7, 0.6, 0.7],
    [0.5, 0.6, 0.5, 0.6]
])
y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

weights = [random.uniform(-1, 1) for _ in range(20)]

learning_rate = 0.01
epochs = 5000

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода"""
    x1, x2, x3, x4 = x
    return (
        coeffs[0] +  # константа
        coeffs[1]*x1 + coeffs[2]*x2 + coeffs[3]*x3 + coeffs[4]*x4 +
        coeffs[5]*x1**2 + coeffs[6]*x2**2 + coeffs[7]*x3**2 + coeffs[8]*x4**2 +
        coeffs[9]*x1*x2 + coeffs[10]*x1*x3 + coeffs[11]*x1*x4 +
        coeffs[12]*x2*x3 + coeffs[13]*x2*x4 + coeffs[14]*x3*x4 +
        coeffs[15]*x1*x2*x3 + coeffs[16]*x1*x2*x4 +
        coeffs[17]*x1*x3*x4 + coeffs[18]*x2*x3*x4 +
        coeffs[19]*x1*x2*x3*x4
    )

# Обучение без регуляризации
for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients = [
            1,                  # w0 (константа)
            x1,                 # w1
            x2,                 # w2
            x3,                 # w3
            x4,                 # w4
            x1**2,              # w5 (x1^2)
            x2**2,              # w6 (x2^2)
            x3**2,              # w7 (x3^2)
            x4**2,              # w8 (x4^2)
            x1*x2,              # w9
            x1*x3,              # w10
            x1*x4,              # w11
            x2*x3,              # w12
            x2*x4,              # w13
            x3*x4,              # w14
            x1*x2*x3,           # w15
            x1*x2*x4,           # w16
            x1*x3*x4,           # w17
            x2*x3*x4,           # w18
            x1*x2*x3*x4         # w19
        ]

        for k in range(len(weights)):
            weights[k] -= learning_rate * error * gradients[k]

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error:.6f}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x} -> {pred:.4f} ({y_train[i]})")

# Вывод уравнения
print("\nУравнение с квадратными членами (без регуляризации):")
print(f"y = {weights[0]:.4f} + {weights[1]:.4f}*x1 + {weights[2]:.4f}*x2 + {weights[3]:.4f}*x3 + {weights[4]:.4f}*x4 +")
print(f"    {weights[5]:.4f}*x1^2 + {weights[6]:.4f}*x2^2 + {weights[7]:.4f}*x3^2 + {weights[8]:.4f}*x4^2 +")
print(f"    {weights[9]:.4f}*x1*x2 + {weights[10]:.4f}*x1*x3 + {weights[11]:.4f}*x1*x4 + {weights[12]:.4f}*x2*x3 + {weights[13]:.4f}*x2*x4 + {weights[14]:.4f}*x3*x4 +")
print(f"    {weights[15]:.4f}*x1*x2*x3 + {weights[16]:.4f}*x1*x2*x4 + {weights[17]:.4f}*x1*x3*x4 + {weights[18]:.4f}*x2*x3*x4 +")
print(f"    {weights[19]:.4f}*x1*x2*x3*x4")

Эпоха 0, Ошибка: 62.204413
Эпоха 500, Ошибка: 0.903051
Эпоха 1000, Ошибка: 0.584696
Эпоха 1500, Ошибка: 0.425831
Эпоха 2000, Ошибка: 0.338249
Эпоха 2500, Ошибка: 0.284330
Эпоха 3000, Ошибка: 0.247634
Эпоха 3500, Ошибка: 0.220683
Эпоха 4000, Ошибка: 0.199866
Эпоха 4500, Ошибка: 0.183281

Результаты:
Вход -> Предсказание (Истинное значение)
[0.5 0.2 0.1 0. ] -> -0.0848 (0)
[0.6 0.3 0.2 0.1] -> 0.2169 (0)
[0.4 0.1 0.1 0. ] -> 0.0330 (0)
[0.7 0.4 0.6 0.3] -> 1.1146 (1)
[0.8 0.5 0.5 0.4] -> 1.0509 (1)
[0.6 0.3 0.4 0.2] -> 0.7764 (1)
[0.3 0.8 0.7 0.9] -> 2.1139 (2)
[0.4 0.9 0.8 0.8] -> 1.9512 (2)
[0.2 0.7 0.6 0.7] -> 2.0335 (2)
[0.5 0.6 0.5 0.6] -> 1.8320 (2)

Уравнение с квадратными членами (без регуляризации):
y = 0.2338 + -0.5063*x1 + 0.1529*x2 + 1.8735*x3 + 1.6975*x4 +
    -1.4303*x1^2 + 0.4476*x2^2 + -0.2387*x3^2 + 0.1850*x4^2 +
    0.5169*x1*x2 + 0.0771*x1*x3 + 1.7575*x1*x4 + 0.4151*x2*x3 + -1.0365*x2*x4 + 0.1171*x3*x4 +
    -0.5172*x1*x2*x3 + 1.0929*x1*x2*x4 + -0.7211*x1*x3*x4 + -2.27