<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/LSTM_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import random
import numpy as np
from keras import models, layers
import tensorflow as tf

# Проверяем доступные устройства
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  1


In [49]:
max_path_length = 15
center = (7, 7)
number_of_maps = 1000


def generate_map():
    game_map = [[0 for _ in range(max_path_length)] for _ in range(max_path_length)]
    game_map[center[0]][center[1]] = 2
    while True:
        x, y = random.randint(0, max_path_length-1), random.randint(0, max_path_length-1)
        if (x, y) != center:
            game_map[x][y] = 1
            break

    return game_map, (x, y)

def find_path(start, goal):
    path = []
    x, y = start
    gx, gy = goal

    while (x, y) != (gx, gy):
        if x < gx:
            path.append(0)  # Движение вниз
            x += 1
        elif x > gx:
            path.append(1)  # Движение вверх
            x -= 1

        if y < gy:
            path.append(0.67)  # Движение вправо
            y += 1
        elif y > gy:
            path.append(0.33)  # Движение влево
            y -= 1

    return path

maps = []
paths = []


for _ in range(number_of_maps):
    game_map, goal = generate_map()
    path = find_path(center, goal)

    maps.append(game_map)
    paths.append(path)


for i in range(len(paths)):
    while len(paths[i]) < max_path_length:
        paths[i].append(0)


print("Первая карта:")
for row in maps[0]:
    print(row)
print("Путь к цели:", paths[0])

Первая карта:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Путь к цели: [0, 0.67, 0, 0.67, 0.67, 0.67, 0.67, 0.67, 0, 0, 0, 0, 0, 0, 0]


In [50]:
X = np.array(maps)
y = np.array(paths)

print(X.shape)
print(y.shape)

print(X[1])
print(y[1])

print(len(maps))
print(len(paths))
print(max([len(i) for i in paths]))
print(min([len(i) for i in paths]))

(1000, 15, 15)
(1000, 15)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
[1.   0.67 0.67 0.67 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.  ]
1000
1000
15
15


In [51]:
model = models.Sequential()
model.add(layers.Input(shape=(max_path_length, max_path_length)))
model.add(layers.LSTM(256, return_sequences=False))
model.add(layers.Dense(max_path_length, activation='sigmoid'))


model.compile(loss='mean_squared_error', optimizer='adam')

model.fit(X, y, epochs=100, verbose=1, validation_split=0.2)

model.save('model.keras')

Epoch 1/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.1643 - val_loss: 0.0979
Epoch 2/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0978 - val_loss: 0.0936
Epoch 3/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0993 - val_loss: 0.0939
Epoch 4/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0969 - val_loss: 0.0931
Epoch 5/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0959 - val_loss: 0.0944
Epoch 6/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0963 - val_loss: 0.0941
Epoch 7/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0973 - val_loss: 0.0941
Epoch 8/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0981 - val_loss: 0.0926
Epoch 9/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0941 - val_loss: 0.0926
Epoch 10/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0938 - val_loss: 0.0925
Epoch 11/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0920 - val_loss: 0.0907
Epoch 12/100
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.

In [54]:

model = models.load_model('model.keras')

test_data = [[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]]

test_data = np.array(test_data)

print(test_data)

predictions = model.predict(test_data)
predictions_rounded = np.round(predictions, 2)

print(predictions_rounded[0])

tolerance = 0.05

for i in predictions_rounded[0]:
    if np.isclose(i, 1, atol=tolerance):
        print('Вверх')
    if np.isclose(i, 0, atol=tolerance):
        print('Вниз')
    if np.isclose(i, 0.67, atol=tolerance):
        print('Направо')
    if np.isclose(i, 0.33, atol=tolerance):
        print('Налево')

[[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step
[0.98 0.34 0.98 0.34 0.98 0.34 0.99 0.33 0.99 0.34 0.99 0.33 0.99 0.38
 0.02]
Вверх
Налево
Вверх
Налево
Вверх
Налево
Вверх
Налево
Вверх
Налево
Вверх
Налево
Вверх
Налево
Вниз


In [53]:
test_data = [[[0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 2, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1]]]

test_data = np.array(test_data)