<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/normalize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


def normalize_array_2d(array, max_value=800, new_max_value=255):
    if not isinstance(array, np.ndarray):
        raise TypeError("Input array must be a NumPy array.")
    if array.ndim != 2:
        raise ValueError("Input array must be a two-dimensional array.")
    if np.min(array) < 0:
        raise ValueError("Input array cannot contain negative values.")
    normalized_array = array / max_value
    rescaled_array = normalized_array * new_max_value
    return rescaled_array

def denormalize_array_2d(array, max_value=800, original_min_value=0):
    if not isinstance(array, np.ndarray):
        raise TypeError("Input array must be a NumPy array.")
    if array.ndim != 2:
        raise ValueError("Input array must be a two-dimensional array.")
    if original_min_value >= max_value:
        raise ValueError("Original minimum value must be less than maximum value.")
    rescaled_array = array * (max_value - original_min_value)
    denormalized_array = rescaled_array + original_min_value
    denormalized_array = denormalized_array / 255
    return denormalized_array.astype(array.dtype)

In [5]:
# Пример использования
input_array = np.array([
    [100.0, 600.0, 5.0, 475.0],
    [20.0, 35.0, 200.0, 800.0]
])
normalized_array = normalize_array_2d(input_array, max_value=800, new_max_value=255)
denormalized_array = denormalize_array_2d(normalized_array, max_value=800, original_min_value=0)

print("Исходный массив:")
print(input_array)
print("\nНормализованный массив:")
print(normalized_array)
print("\nДенормализованный массив:")
print(denormalized_array)

Исходный массив:
[[100. 600.   5. 475.]
 [ 20.  35. 200. 800.]]

Нормализованный массив:
[[ 31.875   191.25      1.59375 151.40625]
 [  6.375    11.15625  63.75    255.     ]]

Денормализованный массив:
[[100. 600.   5. 475.]
 [ 20.  35. 200. 800.]]
