<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [220]:
import numpy as np

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1],  # Периметр = 4
    [2, 2, 3, 3],  # Периметр = 10
    [3, 4, 5, 6],  # Периметр = 18
    [2, 3, 2, 3],  # Периметр = 10
    [4, 5, 4, 5],  # Периметр = 18
    [1, 2, 1, 2],  # Периметр = 6
    [5, 5, 5, 5],  # Периметр = 20
    [3, 3, 4, 4],  # Периметр = 14
    [2, 4, 2, 4]   # Периметр = 12
])

# Периметры (целевые значения)
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Нормализация данных (делим на 10 для работы в диапазоне ~0-1)
X = X / 10.0
y = y / 10.0

# Инициализация весов (15 коэффициентов полинома 2-й степени)
weights = np.random.uniform(-0.1, 0.1, size=15)

# Функция вычисления полиномиальных признаков
def get_features(x):
    a, b, c, d = x
    return np.array([
        1,           # свободный член
        a, b, c, d,  # линейные члены
        a*a, b*b, c*c, d*d,  # квадраты
        a*b, a*c, a*d,  # взаимодействия a с остальными
        b*c, b*d, c*d   # взаимодействия остальных
    ])

# Гиперпараметры регуляризации
lambda_l2 = 0.001  # Уменьшил L2, так как задача простая
lambda_l1 = 0.001  # Уменьшил L1 для сохранения признаков
learning_rate = 0.1

# Обучение (градиентный спуск с регуляризацией)
for epoch in range(10000):
    for i in range(len(X)):
        features = get_features(X[i])
        prediction = sum(features * weights)
        error = prediction - y[i]

        # Градиент MSE + L2 + L1
        gradient = error * features
        gradient += 2 * lambda_l2 * weights  # L2-регуляризация
        gradient += lambda_l1 * np.sign(weights)  # L1-регуляризация

        weights -= learning_rate * gradient

    # Логгирование каждые 1000 эпох
    if epoch % 1000 == 0:
        total_error = sum((sum(get_features(X[i]) * weights) - y[i])**2 for i in range(len(X)))
        print(f"Эпоха {epoch}, Ошибка: {total_error:.6f}")

# Проверка на обучающей выборке
print("\nПредсказания vs Истинные значения:")
for i in range(len(X)):
    features = get_features(X[i])
    prediction = sum(features * weights)
    # Возвращаем значения к исходному масштабу (умножаем на 10)
    print(f"{X[i] * 10} → {prediction * 10:.2f} (истинное: {y[i] * 10})")

# Вывод обученных весов (для анализа регуляризации)
print("\nОбученные веса (нормированные):")
print(np.round(weights, 4))

# Предсказание для нового четырехугольника
new_quad = np.array([1.5, 1.5, 2.5, 2.5])  # Стороны нового четырехугольника
new_features = get_features(new_quad / 10.0)  # Нормализуем как обучающие данные
predicted_perimeter = sum(new_features * weights) * 10  # Денормализуем результат

print(f"\nПредсказание периметра для {new_quad}: {predicted_perimeter:.2f}")

Эпоха 0, Ошибка: 1.223852
Эпоха 1000, Ошибка: 0.005214
Эпоха 2000, Ошибка: 0.004758
Эпоха 3000, Ошибка: 0.004730
Эпоха 4000, Ошибка: 0.004728
Эпоха 5000, Ошибка: 0.004728
Эпоха 6000, Ошибка: 0.004728
Эпоха 7000, Ошибка: 0.004728
Эпоха 8000, Ошибка: 0.004728
Эпоха 9000, Ошибка: 0.004728

Предсказания vs Истинные значения:
[1. 1. 1. 1.] → 4.51 (истинное: 4.0)
[2. 2. 3. 3.] → 9.93 (истинное: 10.0)
[3. 4. 5. 6.] → 18.17 (истинное: 18.0)
[2. 3. 2. 3.] → 9.91 (истинное: 10.0)
[4. 5. 4. 5.] → 17.89 (истинное: 18.0)
[1. 2. 1. 2.] → 6.30 (истинное: 6.0)
[5. 5. 5. 5.] → 19.88 (истинное: 20.0)
[3. 3. 4. 4.] → 13.78 (истинное: 14.0)
[2. 4. 2. 4.] → 11.94 (истинное: 12.0)

Обученные веса (нормированные):
[0.1293 0.7054 0.748  0.7997 0.8423 0.0694 0.1561 0.1081 0.1699 0.1073
 0.0903 0.1282 0.1157 0.1645 0.1336]

Предсказание периметра для [1.5 1.5 2.5 2.5]: 8.10


In [221]:
import numpy as np

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1],  # Периметр = 4
    [2, 2, 3, 3],  # Периметр = 10
    [3, 4, 5, 6],  # Периметр = 18
    [2, 3, 2, 3],  # Периметр = 10
    [4, 5, 4, 5],  # Периметр = 18
    [1, 2, 1, 2],  # Периметр = 6
    [5, 5, 5, 5],  # Периметр = 20
    [3, 3, 4, 4],  # Периметр = 14
    [2, 4, 2, 4]   # Периметр = 12
])

# Периметры (целевые значения)
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Нормализация данных
X = X / 10.0
y = y / 10.0

# Функция создания матрицы полиномиальных признаков
def create_poly_matrix(X):
    a, b, c, d = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
    return np.column_stack([
        np.ones(len(X)),  # свободный член
        a, b, c, d,      # линейные члены
        a*a, b*b, c*c, d*d,  # квадраты
        a*b, a*c, a*d,   # взаимодействия
        b*c, b*d, c*d
    ])

# Создаем матрицу признаков
X_poly = create_poly_matrix(X)

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_poly.shape[1])

# Гиперпараметры
lambda_l2 = 0.001
lambda_l1 = 0.001
learning_rate = 0.1
epochs = 10000

# Обучение с матричными операциями
for epoch in range(epochs):
    # Прямое распространение
    predictions = X_poly @ weights

    # Ошибка
    errors = predictions - y

    # Градиент
    gradient = (X_poly.T @ errors) / len(X)
    gradient += 2 * lambda_l2 * weights  # L2
    gradient += lambda_l1 * np.sign(weights)  # L1

    # Обновление весов
    weights -= learning_rate * gradient

    # Логирование
    if epoch % 1000 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch}, Loss: {loss:.6f}")

# Проверка
print("\nПредсказания vs Истинные значения:")
predictions = X_poly @ weights
for i in range(len(X)):
    print(f"{X[i] * 10} → {predictions[i] * 10:.2f} (истинное: {y[i] * 10})")

# Веса модели
print("\nОбученные веса:")
print(np.round(weights, 4))

# Предсказание для нового примера
new_quad = np.array([1.5, 1.5, 2.5, 2.5]) / 10.0
new_features = create_poly_matrix(new_quad[np.newaxis, :])
prediction = (new_features @ weights)[0] * 10
print(f"\nПредсказание периметра для [1.5, 1.5, 2.5, 2.5]: {prediction:.2f}")

Эпоха 0, Loss: 1.633028
Эпоха 1000, Loss: 0.001461
Эпоха 2000, Loss: 0.001166
Эпоха 3000, Loss: 0.000987
Эпоха 4000, Loss: 0.000868
Эпоха 5000, Loss: 0.000787
Эпоха 6000, Loss: 0.000730
Эпоха 7000, Loss: 0.000689
Эпоха 8000, Loss: 0.000660
Эпоха 9000, Loss: 0.000639

Предсказания vs Истинные значения:
[1. 1. 1. 1.] → 4.51 (истинное: 4.0)
[2. 2. 3. 3.] → 9.87 (истинное: 10.0)
[3. 4. 5. 6.] → 18.12 (истинное: 18.0)
[2. 3. 2. 3.] → 9.87 (истинное: 10.0)
[4. 5. 4. 5.] → 17.82 (истинное: 18.0)
[1. 2. 1. 2.] → 6.29 (истинное: 6.0)
[5. 5. 5. 5.] → 19.80 (истинное: 20.0)
[3. 3. 4. 4.] → 13.70 (истинное: 14.0)
[2. 4. 2. 4.] → 11.91 (истинное: 12.0)

Обученные веса:
[0.135  0.676  0.7341 0.7752 0.8396 0.0851 0.1582 0.1081 0.1779 0.1054
 0.1032 0.1406 0.1177 0.1832 0.149 ]

Предсказание периметра для [1.5, 1.5, 2.5, 2.5]: 8.06


In [222]:
import numpy as np
from tabulate import tabulate  # Для красивого вывода таблиц

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1],  # Периметр = 4
    [2, 2, 3, 3],  # Периметр = 10
    [3, 4, 5, 6],  # Периметр = 18
    [2, 3, 2, 3],  # Периметр = 10
    [4, 5, 4, 5],  # Периметр = 18
    [1, 2, 1, 2],  # Периметр = 6
    [5, 5, 5, 5],  # Периметр = 20
    [3, 3, 4, 4],  # Периметр = 14
    [2, 4, 2, 4]   # Периметр = 12
])

# Периметры (целевые значения)
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Нормализация данных
X_norm = X / 10.0
y_norm = y / 10.0

# Функция создания матрицы полиномиальных признаков с названиями признаков
def create_poly_matrix(X):
    a, b, c, d = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
    features = np.column_stack([
        np.ones(len(X)),  # свободный член
        a, b, c, d,      # линейные члены
        a*a, b*b, c*c, d*d,  # квадраты
        a*b, a*c, a*d,   # взаимодействия
        b*c, b*d, c*d
    ])

    # Названия признаков для красивого вывода
    feature_names = [
        '1', 'a', 'b', 'c', 'd',
        'a²', 'b²', 'c²', 'd²',
        'a*b', 'a*c', 'a*d',
        'b*c', 'b*d', 'c*d'
    ]

    return features, feature_names

# Создаем матрицу признаков и получаем названия
X_poly, feature_names = create_poly_matrix(X_norm)

# Красивый вывод матрицы признаков
print("Матрица полиномиальных признаков:")
# Подготовка данных для вывода (первые 5 строк для примера)
headers = ["Пример"] + feature_names
table_data = []
for i in range(min(5, len(X))):  # Выведем первые 5 примеров
    row = [f"Образец {i+1} (Периметр={y[i]})"] + [f"{val:.3f}" for val in X_poly[i]]
    table_data.append(row)

print(tabulate(table_data, headers=headers, tablefmt="grid", stralign="center"))
print("\n" + "..."*30 + "\n")  # Разделитель для остального вывода

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_poly.shape[1])

# Гиперпараметры
lambda_l2 = 0.001
lambda_l1 = 0.001
learning_rate = 0.1
epochs = 10000

# Обучение с матричными операциями
for epoch in range(epochs):
    predictions = X_poly @ weights
    errors = predictions - y_norm
    gradient = (X_poly.T @ errors) / len(X)
    gradient += 2 * lambda_l2 * weights
    gradient += lambda_l1 * np.sign(weights)
    weights -= learning_rate * gradient

    if epoch % 1000 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Вывод результатов
print("\nРезультаты обучения:")
results = []
for i in range(len(X)):
    pred = (X_poly[i] @ weights) * 10
    results.append([
        f"[{', '.join(map(str, X[i]))}]",
        y[i],
        f"{pred:.2f}",
        f"{abs(pred - y[i]):.2f}"
    ])

print(tabulate(results,
             headers=["Стороны", "Истинный периметр", "Предсказание", "Ошибка"],
             tablefmt="grid",
             stralign="center"))

# Вывод весов с названиями признаков
print("\nОбученные веса:")
weight_table = list(zip(feature_names, np.round(weights, 4)))
print(tabulate(weight_table,
              headers=["Признак", "Вес"],
              tablefmt="grid",
              stralign="center"))

# Предсказание для нового примера
new_quad = np.array([1.5, 1.5, 2.5, 2.5])
new_features, _ = create_poly_matrix((new_quad / 10.0)[np.newaxis, :])
prediction = (new_features @ weights)[0] * 10

print(f"\nПредсказание для нового четырехугольника:")
print(f"Стороны: {new_quad}")
print(f"Предсказанный периметр: {prediction:.2f}")
print(f"Ожидаемый периметр: {sum(new_quad)}")

Матрица полиномиальных признаков:
+-------------------------+-----+-----+-----+-----+-----+------+------+------+------+-------+-------+-------+-------+-------+-------+
|         Пример          |   1 |   a |   b |   c |   d |   a² |   b² |   c² |   d² |   a*b |   a*c |   a*d |   b*c |   b*d |   c*d |
+=========================+=====+=====+=====+=====+=====+======+======+======+======+=======+=======+=======+=======+=======+=======+
| Образец 1 (Периметр=4)  |   1 | 0.1 | 0.1 | 0.1 | 0.1 | 0.01 | 0.01 | 0.01 | 0.01 |  0.01 |  0.01 |  0.01 |  0.01 |  0.01 |  0.01 |
+-------------------------+-----+-----+-----+-----+-----+------+------+------+------+-------+-------+-------+-------+-------+-------+
| Образец 2 (Периметр=10) |   1 | 0.2 | 0.2 | 0.3 | 0.3 | 0.04 | 0.04 | 0.09 | 0.09 |  0.04 |  0.06 |  0.06 |  0.06 |  0.06 |  0.09 |
+-------------------------+-----+-----+-----+-----+-----+------+------+------+------+-------+-------+-------+-------+-------+-------+
| Образец 3 (Периметр=18) | 

In [223]:
import numpy as np
from tabulate import tabulate

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1], [2, 2, 3, 3], [3, 4, 5, 6],
    [2, 3, 2, 3], [4, 5, 4, 5], [1, 2, 1, 2],
    [5, 5, 5, 5], [3, 3, 4, 4], [2, 4, 2, 4]
])
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Нормализация данных
X_norm = X / 10.0
y_norm = y / 10.0

def create_poly_matrix(X):
    a, b, c, d = X[:, 0], X[:, 1], X[:, 2], X[:, 3]

    # Квадратичные и кубические члены
    squares = np.column_stack([a*a, b*b, c*c, d*d])
    cubes = np.column_stack([a**3, b**3, c**3, d**3])

    # Взаимодействия
    interactions = np.column_stack([
        a*b, a*c, a*d, b*c, b*d, c*d,
        a*b*c, a*b*d, a*c*d, b*c*d,
        a*a*b, a*a*c, a*a*d, b*b*a, b*b*c, b*b*d,
        c*c*a, c*c*b, c*c*d, d*d*a, d*d*b, d*d*c
    ])

    features = np.column_stack([
        np.ones(len(X)),  # свободный член
        a, b, c, d,      # линейные
        squares, cubes,   # квадраты и кубы
        interactions      # взаимодействия
    ])

    feature_names = [
        '1', 'a', 'b', 'c', 'd',
        *[f'{x}²' for x in ['a', 'b', 'c', 'd']],
        *[f'{x}³' for x in ['a', 'b', 'c', 'd']],
        'ab', 'ac', 'ad', 'bc', 'bd', 'cd',
        'abc', 'abd', 'acd', 'bcd',
        'a²b', 'a²c', 'a²d', 'b²a', 'b²c', 'b²d',
        'c²a', 'c²b', 'c²d', 'd²a', 'd²b', 'd²c'
    ]

    return features, feature_names

X_poly, feature_names = create_poly_matrix(X_norm)

# Вывод информации о признаках
print(f"Всего признаков: {len(feature_names)}")
print("Пример первых 15 признаков:", feature_names[:15])
print("Пример последних 10 признаков:", feature_names[-10:])
print("\nПервые 3 строки матрицы признаков:")

# Красивый вывод первых 3 строк
headers = ["Пример"] + feature_names[:10] + ["..."] + feature_names[-5:]
table_data = []
for i in range(3):
    row = [f"Обр. {i+1}"] + [f"{x:.3f}" for x in X_poly[i,:10]] + ["..."] + [f"{x:.3f}" for x in X_poly[i,-5:]]
    table_data.append(row)

print(tabulate(table_data, headers=headers, tablefmt="grid", stralign="center", floatfmt=".3f"))

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_poly.shape[1])

# Обучение с регуляризацией
lambda_l2 = 0.001
lambda_l1 = 0.001
learning_rate = 0.01  # Уменьшили learning rate из-за сложности модели
epochs = 5000

for epoch in range(epochs):
    predictions = X_poly @ weights
    errors = predictions - y_norm
    gradient = (X_poly.T @ errors) / len(X)
    gradient += 2 * lambda_l2 * weights + lambda_l1 * np.sign(weights)
    weights -= learning_rate * gradient

    if epoch % 500 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Результаты
print("\nТоп-10 наиболее значимых признаков:")
sorted_weights = sorted(zip(feature_names, weights), key=lambda x: -abs(x[1]))
print(tabulate(sorted_weights[:10], headers=["Признак", "Вес"], tablefmt="grid"))

# Предсказание
new_quad = np.array([1.5, 1.5, 2.5, 2.5])
new_features, _ = create_poly_matrix((new_quad / 10.0)[np.newaxis, :])
prediction = (new_features @ weights)[0] * 10

print(f"\nПредсказание для {new_quad}:")
print(f"Ожидаемый периметр: {sum(new_quad)}")
print(f"Предсказанный периметр: {prediction:.2f}")
print(f"Ошибка: {abs(prediction - sum(new_quad)):.2f}")

Всего признаков: 35
Пример первых 15 признаков: ['1', 'a', 'b', 'c', 'd', 'a²', 'b²', 'c²', 'd²', 'a³', 'b³', 'c³', 'd³', 'ab', 'ac']
Пример последних 10 признаков: ['a²d', 'b²a', 'b²c', 'b²d', 'c²a', 'c²b', 'c²d', 'd²a', 'd²b', 'd²c']

Первые 3 строки матрицы признаков:
+----------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
|  Пример  |     1 |     a |     b |     c |     d |    a² |    b² |    c² |    d² |    a³ |  ...  |   c²b |   c²d |   d²a |   d²b |   d²c |
+==========+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+=======+
|  Обр. 1  | 1.000 | 0.100 | 0.100 | 0.100 | 0.100 | 0.010 | 0.010 | 0.010 | 0.010 | 0.001 |  ...  | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 |
+----------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+-------+
|  Обр. 2  | 1.000 | 0.

In [225]:
import numpy as np
from tabulate import tabulate
from itertools import combinations_with_replacement

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1], [2, 2, 3, 3], [3, 4, 5, 6],
    [2, 3, 2, 3], [4, 5, 4, 5], [1, 2, 1, 2],
    [5, 5, 5, 5], [3, 3, 4, 4], [2, 4, 2, 4]
])
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Нормализация данных
X_norm = X / 10.0
y_norm = y / 10.0

def generate_feature_names(max_degree=4):
    """Генерация имен признаков до max_degree степени"""
    variables = ['a', 'b', 'c', 'd']
    feature_names = ['1']  # Свободный член

    for degree in range(1, max_degree+1):
        for comb in combinations_with_replacement(variables, degree):
            # Группируем одинаковые переменные (a*a -> a²)
            counts = {}
            for var in comb:
                counts[var] = counts.get(var, 0) + 1

            # Создаем имя признака
            name = ''
            for var in sorted(counts.keys()):
                if counts[var] > 1:
                    name += f'{var}^{counts[var]}'
                else:
                    name += var
            feature_names.append(name)

    return feature_names

def create_poly_matrix(X, max_degree=4):
    """Создание матрицы признаков до max_degree степени"""
    a, b, c, d = X[:, 0], X[:, 1], X[:, 2], X[:, 3]
    features = [np.ones(len(X))]  # Свободный член

    # Генерация признаков всех степеней
    variables = {'a': a, 'b': b, 'c': c, 'd': d}
    for degree in range(1, max_degree+1):
        for comb in combinations_with_replacement(variables.keys(), degree):
            feature = np.ones(len(X))
            for var in comb:
                feature *= variables[var]
            features.append(feature)

    return np.column_stack(features), generate_feature_names(max_degree)

# Создаем матрицу признаков 4-й степени
X_poly, feature_names = create_poly_matrix(X_norm, max_degree=4)

# Вывод информации о признаках
print(f"Всего признаков: {len(feature_names)}")
print("Примеры признаков:")
print("Линейные:", feature_names[1:5])
print("Квадраты:", feature_names[5:9])
print("Кубы:", feature_names[9:13])
print("4-я степень:", feature_names[13:17])
print("Взаимодействия 2 порядка:", feature_names[17:23])
print("Взаимодействия 3 порядка:", feature_names[23:31])
print("Взаимодействия 4 порядка:", feature_names[31:])

# Инициализация весов
weights = np.random.uniform(-0.05, 0.05, size=X_poly.shape[1])

# Гиперпараметры
lambda_l2 = 0.0001  # Уменьшенный коэффициент регуляризации
lambda_l1 = 0.0001
learning_rate = 0.001  # Меньше learning rate из-за сложности модели
epochs = 10000

# Обучение с регуляризацией
for epoch in range(epochs):
    predictions = X_poly @ weights
    errors = predictions - y_norm
    gradient = (X_poly.T @ errors) / len(X)
    gradient += 2 * lambda_l2 * weights + lambda_l1 * np.sign(weights)
    weights -= learning_rate * gradient

    if epoch % 1000 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Анализ результатов
print("\nТоп-15 наиболее значимых признаков:")
sorted_weights = sorted(zip(feature_names, weights),
                      key=lambda x: -abs(x[1]))
print(tabulate(sorted_weights[:15], headers=["Признак", "Вес"], tablefmt="grid"))

# Предсказание
test_quads = np.array([
    [1.5, 1.5, 2.5, 2.5],  # Периметр = 8
    [2.0, 3.0, 2.0, 3.0],  # Периметр = 10
    [4.0, 5.0, 6.0, 5.0]   # Периметр = 20
])

print("\nТестирование на новых данных:")
for quad in test_quads:
    features, _ = create_poly_matrix((quad / 10.0)[np.newaxis, :], max_degree=4)
    prediction = (features @ weights)[0] * 10
    print(f"Стороны: {quad}")
    print(f"Ожидаемый периметр: {sum(quad)}")
    print(f"Предсказанный периметр: {prediction:.4f}")
    print(f"Ошибка: {abs(prediction - sum(quad)):.4f}")
    print("-" * 40)

Всего признаков: 70
Примеры признаков:
Линейные: ['a', 'b', 'c', 'd']
Квадраты: ['a^2', 'ab', 'ac', 'ad']
Кубы: ['b^2', 'bc', 'bd', 'c^2']
4-я степень: ['cd', 'd^2', 'a^3', 'a^2b']
Взаимодействия 2 порядка: ['a^2c', 'a^2d', 'ab^2', 'abc', 'abd', 'ac^2']
Взаимодействия 3 порядка: ['acd', 'ad^2', 'b^3', 'b^2c', 'b^2d', 'bc^2', 'bcd', 'bd^2']
Взаимодействия 4 порядка: ['c^3', 'c^2d', 'cd^2', 'd^3', 'a^4', 'a^3b', 'a^3c', 'a^3d', 'a^2b^2', 'a^2bc', 'a^2bd', 'a^2c^2', 'a^2cd', 'a^2d^2', 'ab^3', 'ab^2c', 'ab^2d', 'abc^2', 'abcd', 'abd^2', 'ac^3', 'ac^2d', 'acd^2', 'ad^3', 'b^4', 'b^3c', 'b^3d', 'b^2c^2', 'b^2cd', 'b^2d^2', 'bc^3', 'bc^2d', 'bcd^2', 'bd^3', 'c^4', 'c^3d', 'c^2d^2', 'cd^3', 'd^4']
Эпоха    0, Loss: 1.729839
Эпоха 1000, Loss: 0.117155
Эпоха 2000, Loss: 0.048126
Эпоха 3000, Loss: 0.037357
Эпоха 4000, Loss: 0.030473
Эпоха 5000, Loss: 0.025111
Эпоха 6000, Loss: 0.020887
Эпоха 7000, Loss: 0.017554
Эпоха 8000, Loss: 0.014923
Эпоха 9000, Loss: 0.012844

Топ-15 наиболее значимых призн

In [235]:
import numpy as np
from tabulate import tabulate

# Данные: стороны четырехугольника (a, b, c, d) и их периметры (a+b+c+d)
X = np.array([
    [1, 1, 1, 1],  # Периметр = 4
    [2, 2, 3, 3],  # Периметр = 10
    [3, 4, 5, 6],  # Периметр = 18
    [2, 3, 2, 3],  # Периметр = 10
    [4, 5, 4, 5],  # Периметр = 18
    [1, 2, 1, 2],  # Периметр = 6
    [5, 5, 5, 5],  # Периметр = 20
    [3, 3, 4, 4],  # Периметр = 14
    [2, 4, 2, 4]   # Периметр = 12
])

# Периметры (целевые значения)
y = np.array([4, 10, 18, 10, 18, 6, 20, 14, 12])

# Функция создания матрицы ЛИНЕЙНЫХ признаков
def create_linear_matrix(X):
    # Добавляем свободный член (константу) и линейные члены
    return np.column_stack([
        np.ones(len(X)),  # свободный член
        X[:, 0],  # a
        X[:, 1],  # b
        X[:, 2],  # c
        X[:, 3]   # d
    ])

# Создаем матрицу признаков
X_linear = create_linear_matrix(X_norm)
feature_names = ['1', 'a', 'b', 'c', 'd']

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_linear.shape[1])

# Гиперпараметры
learning_rate = 0.01
epochs = 1000

# Обучение (градиентный спуск)
for epoch in range(epochs):
    # Прямое распространение
    predictions = X_linear @ weights

    # Ошибка
    errors = predictions - y_norm

    # Градиент
    gradient = (X_linear.T @ errors) / len(X)

    # Обновление весов
    weights -= learning_rate * gradient

    # Логирование
    if epoch % 100 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Вывод результатов
print("\nОбученные веса:")
print(tabulate(zip(feature_names, weights),
              headers=["Признак", "Вес"],
              tablefmt="grid",
              floatfmt=".4f"))

# Проверка на обучающей выборке
print("\nПроверка на обучающих данных:")
results = []
for i in range(len(X)):
    pred = X_linear[i] @ weights
    results.append([
        f"{X[i]}",
        y[i],
        f"{pred:.2f}",
        f"{abs(pred - y[i]):.2f}"
    ])

print(tabulate(results,
              headers=["Стороны", "Истинный периметр", "Предсказание", "Ошибка"],
              tablefmt="grid"))

# Предсказание для новых данных
test_quads = np.array([
    [1.5, 1.5, 2.5, 2.5],  # Периметр = 8
    [2.0, 3.0, 2.0, 3.0],  # Периметр = 10
    [4.0, 5.0, 6.0, 5.0]   # Периметр = 20
])

print("\nТестирование на новых данных:")
for quad in test_quads:
    # Создаем вектор признаков (с свободным членом)
    quad_features = np.concatenate([[1], quad])
    prediction = quad_features @ weights
    print(f"Стороны: {quad}")
    print(f"Ожидаемый периметр: {sum(quad)}")
    print(f"Предсказанный периметр: {prediction:.2f}")
    print(f"Ошибка: {abs(prediction - sum(quad)):.2f}")
    print("-" * 40)

Эпоха    0, Loss: 195.968761
Эпоха  100, Loss: 0.019895
Эпоха  200, Loss: 0.011135
Эпоха  300, Loss: 0.006763
Эпоха  400, Loss: 0.004407
Эпоха  500, Loss: 0.003035
Эпоха  600, Loss: 0.002177
Эпоха  700, Loss: 0.001607
Эпоха  800, Loss: 0.001208
Эпоха  900, Loss: 0.000919

Обученные веса:
+-----------+--------+
| Признак   |    Вес |
+===========+========+
| 1         | 0.0722 |
+-----------+--------+
| a         | 0.9605 |
+-----------+--------+
| b         | 1.0279 |
+-----------+--------+
| c         | 1.0448 |
+-----------+--------+
| d         | 0.9492 |
+-----------+--------+

Проверка на обучающих данных:
+-----------+---------------------+----------------+----------+
| Стороны   |   Истинный периметр |   Предсказание |   Ошибка |
+===========+=====================+================+==========+
| [1 1 1 1] |                   4 |           4.05 |     0.05 |
+-----------+---------------------+----------------+----------+
| [2 2 3 3] |                  10 |          10.03 |     0.03

In [236]:
import numpy as np
from tabulate import tabulate

# Данные: стороны прямоугольника (a, b) и их площади (a*b)
X = np.array([
    [1, 1],  # Площадь = 1
    [2, 2],  # Площадь = 4
    [3, 3],  # Площадь = 9
    [1, 2],  # Площадь = 2
    [2, 3],  # Площадь = 6
    [3, 4],  # Площадь = 12
    [1, 3],  # Площадь = 3
    [2, 4],  # Площадь = 8
    [3, 5]   # Площадь = 15
])

# Площади (целевые значения)
y = np.array([1, 4, 9, 2, 6, 12, 3, 8, 15])

# Функция создания матрицы полиномиальных признаков (2-й степени)
def create_poly_matrix(X):
    a, b = X[:, 0], X[:, 1]
    return np.column_stack([
        np.ones(len(X)),  # свободный член
        a, b,            # линейные члены
        a*b,             # взаимодействие
        a**2, b**2       # квадраты
    ])

# Создаем матрицу признаков
X_poly = create_poly_matrix(X)
feature_names = ['1', 'a', 'b', 'a*b', 'a²', 'b²']

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_poly.shape[1])

# Гиперпараметры
learning_rate = 0.001
epochs = 5000

# Обучение (градиентный спуск)
for epoch in range(epochs):
    # Прямое распространение
    predictions = X_poly @ weights

    # Ошибка
    errors = predictions - y

    # Градиент
    gradient = (X_poly.T @ errors) / len(X)

    # Обновление весов
    weights -= learning_rate * gradient

    # Логирование
    if epoch % 500 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Вывод результатов
print("\nОбученные веса:")
print(tabulate(zip(feature_names, weights),
              headers=["Признак", "Вес"],
              tablefmt="grid",
              floatfmt=".4f"))

# Проверка на обучающей выборке
print("\nПроверка на обучающих данных:")
results = []
for i in range(len(X)):
    pred = X_poly[i] @ weights
    results.append([
        f"{X[i]}",
        y[i],
        f"{pred:.2f}",
        f"{abs(pred - y[i]):.2f}"
    ])

print(tabulate(results,
              headers=["Стороны", "Истинная площадь", "Предсказание", "Ошибка"],
              tablefmt="grid"))

# Предсказание для новых данных
test_rects = np.array([
    [2.5, 2.5],  # Площадь = 6.25
    [1.5, 3.5],  # Площадь = 5.25
    [4.0, 5.0]   # Площадь = 20.0
])

print("\nТестирование на новых данных:")
for rect in test_rects:
    # Создаем вектор признаков
    a, b = rect
    rect_features = np.array([1, a, b, a*b, a**2, b**2])
    prediction = rect_features @ weights
    print(f"Стороны: {rect}")
    print(f"Ожидаемая площадь: {a*b:.2f}")
    print(f"Предсказанная площадь: {prediction:.2f}")
    print(f"Ошибка: {abs(prediction - a*b):.2f}")
    print("-" * 40)

Эпоха    0, Loss: 73.392796
Эпоха  500, Loss: 0.035176
Эпоха 1000, Loss: 0.021463
Эпоха 1500, Loss: 0.016661
Эпоха 2000, Loss: 0.014650
Эпоха 2500, Loss: 0.013606
Эпоха 3000, Loss: 0.012908
Эпоха 3500, Loss: 0.012343
Эпоха 4000, Loss: 0.011836
Эпоха 4500, Loss: 0.011364

Обученные веса:
+-----------+---------+
| Признак   |     Вес |
+===========+=========+
| 1         | -0.0159 |
+-----------+---------+
| a         |  0.0622 |
+-----------+---------+
| b         | -0.1378 |
+-----------+---------+
| a*b       |  0.5671 |
+-----------+---------+
| a²        |  0.3079 |
+-----------+---------+
| b²        |  0.1694 |
+-----------+---------+

Проверка на обучающих данных:
+-----------+--------------------+----------------+----------+
| Стороны   |   Истинная площадь |   Предсказание |   Ошибка |
+===========+====================+================+==========+
| [1 1]     |                  1 |           0.95 |     0.05 |
+-----------+--------------------+----------------+----------+
| [2 2

In [250]:
import numpy as np
from tabulate import tabulate

# Данные: стороны прямоугольника (a, b) и их площади (a*b)
X = np.array([
    [1, 1],  # Площадь = 1
    [2, 2],  # Площадь = 4
    [3, 3],  # Площадь = 9
    [1, 2],  # Площадь = 2
    [2, 3],  # Площадь = 6
    [3, 4],  # Площадь = 12
    [1, 3],  # Площадь = 3
    [2, 4],  # Площадь = 8
    [3, 5]   # Площадь = 15
])

# Площади (целевые значения)
y = np.array([1, 4, 9, 2, 6, 12, 3, 8, 15])

# Функция создания матрицы полиномиальных признаков (2-й степени)
def create_poly_matrix(X):
    a, b = X[:, 0], X[:, 1]
    return np.column_stack([
        np.ones(len(X)),  # свободный член
        a, b,            # линейные члены
        a*b,             # взаимодействие
        a**2, b**2       # квадраты
    ])

# Создаем матрицу признаков
X_poly = create_poly_matrix(X)
feature_names = ['1', 'a', 'b', 'a*b', 'a²', 'b²']

# Инициализация весов
weights = np.random.uniform(-0.1, 0.1, size=X_poly.shape[1])

# Гиперпараметры Adam
learning_rate = 0.01
epochs = 5000
beta1 = 0.9
beta2 = 0.999
epsilon = 1e-8

# Инициализация моментов для Adam
m = np.zeros_like(weights)
v = np.zeros_like(weights)

# Обучение с Adam optimizer
for epoch in range(1, epochs + 1):
    # Прямое распространение
    predictions = X_poly @ weights

    # Ошибка
    errors = predictions - y

    # Градиент
    gradient = (X_poly.T @ errors) / len(X)

    # Обновление моментов Adam
    m = beta1 * m + (1 - beta1) * gradient
    v = beta2 * v + (1 - beta2) * (gradient ** 2)

    # Коррекция моментов (bias correction)
    m_hat = m / (1 - beta1 ** epoch)
    v_hat = v / (1 - beta2 ** epoch)

    # Обновление весов
    weights -= learning_rate * m_hat / (np.sqrt(v_hat) + epsilon)

    # Логирование
    if epoch % 500 == 0:
        loss = np.mean(errors**2)
        print(f"Эпоха {epoch:4d}, Loss: {loss:.6f}")

# Вывод результатов
print("\nОбученные веса:")
print(tabulate(zip(feature_names, weights),
              headers=["Признак", "Вес"],
              tablefmt="grid",
              floatfmt=".4f"))

# Проверка на обучающей выборке
print("\nПроверка на обучающих данных:")
results = []
for i in range(len(X)):
    pred = X_poly[i] @ weights
    results.append([
        f"{X[i]}",
        y[i],
        f"{pred:.2f}",
        f"{abs(pred - y[i]):.2f}"
    ])

print(tabulate(results,
              headers=["Стороны", "Истинная площадь", "Предсказание", "Ошибка"],
              tablefmt="grid"))

# Предсказание для новых данных
test_rects = np.array([
    [2.5, 2.5],  # Площадь = 6.25
    [1.5, 3.5],  # Площадь = 5.25
    [4.0, 5.0]   # Площадь = 20.0
])

print("\nТестирование на новых данных:")
for rect in test_rects:
    # Создаем вектор признаков
    a, b = rect
    rect_features = np.array([1, a, b, a*b, a**2, b**2])
    prediction = rect_features @ weights
    print(f"Стороны: {rect}")
    print(f"Ожидаемая площадь: {a*b:.2f}")
    print(f"Предсказанная площадь: {prediction:.2f}")
    print(f"Ошибка: {abs(prediction - a*b):.2f}")
    print("-" * 40)

Эпоха  500, Loss: 0.044502
Эпоха 1000, Loss: 0.024099
Эпоха 1500, Loss: 0.020778
Эпоха 2000, Loss: 0.017182
Эпоха 2500, Loss: 0.013648
Эпоха 3000, Loss: 0.010472
Эпоха 3500, Loss: 0.007820
Эпоха 4000, Loss: 0.005704
Эпоха 4500, Loss: 0.004031
Эпоха 5000, Loss: 0.002699

Обученные веса:
+-----------+---------+
| Признак   |     Вес |
+===========+=========+
| 1         |  0.0222 |
+-----------+---------+
| a         |  0.1904 |
+-----------+---------+
| b         | -0.1910 |
+-----------+---------+
| a*b       |  0.7696 |
+-----------+---------+
| a²        |  0.1261 |
+-----------+---------+
| b²        |  0.1082 |
+-----------+---------+

Проверка на обучающих данных:
+-----------+--------------------+----------------+----------+
| Стороны   |   Истинная площадь |   Предсказание |   Ошибка |
+===========+====================+================+==========+
| [1 1]     |                  1 |           1.03 |     0.03 |
+-----------+--------------------+----------------+----------+
| [2 2]