<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

# Данные (X нормирован, Y — один выход 0 или 1)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
], dtype=np.float32) / 10.0  # Нормализация

y_train = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=np.float32)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)

# Инициализация весов (5 членов: 1, x1, x2, x3, x4)
weights = np.random.uniform(-0.1, 0.1, size=5).astype(np.float32)

print("\nНачальные веса:")
print(weights)
print("\n")

learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Вычисление линейного полинома: prediction = w0 + w1*x1 + w2*x2 + w3*x3 + w4*x4
        terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
        prediction = np.dot(terms, weights)
        error = prediction - target
        total_error += error ** 2

        # Обновление весов
        weights -= learning_rate * error * terms

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

print("\nОбученные веса:")
print(weights)

# Проверка
print("\nРезультаты:")
for i in range(len(X_train)):
    x = X_train[i]
    terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
    pred = np.dot(terms, weights)
    print(f"{x * 10} -> {pred:.4f} (Истинное: {y_train[i]})")

X_train:
[[0.5 0.2 0.1 0. ]
 [0.6 0.3 0.2 0.1]
 [0.4 0.1 0.1 0. ]
 [0.7 0.4 0.6 0.3]
 [0.8 0.5 0.5 0.4]
 [0.6 0.3 0.4 0.2]
 [0.3 0.8 0.7 0.9]
 [0.4 0.9 0.8 0.8]
 [0.2 0.7 0.6 0.7]]

y_train:
[0. 0. 0. 1. 1. 1. 1. 0. 1.]

Начальные веса:
[-0.01309192 -0.08581145 -0.05158012  0.0292474  -0.07811698]


Эпоха 0, Ошибка: 3.4911158084869385
Эпоха 500, Ошибка: 0.9781957864761353
Эпоха 1000, Ошибка: 0.7724632024765015
Эпоха 1500, Ошибка: 0.7183164358139038
Эпоха 2000, Ошибка: 0.7021081447601318
Эпоха 2500, Ошибка: 0.6966086626052856
Эпоха 3000, Ошибка: 0.6944998502731323
Эпоха 3500, Ошибка: 0.6936099529266357
Эпоха 4000, Ошибка: 0.6932099461555481
Эпоха 4500, Ошибка: 0.6930245757102966
Эпоха 5000, Ошибка: 0.6929359436035156
Эпоха 5500, Ошибка: 0.6928939819335938
Эпоха 6000, Ошибка: 0.6928738355636597
Эпоха 6500, Ошибка: 0.6928644180297852
Эпоха 7000, Ошибка: 0.6928602457046509
Эпоха 7500, Ошибка: 0.6928602457046509
Эпоха 8000, Ошибка: 0.6928602457046509
Эпоха 8500, Ошибка: 0.6928602457046509
Э

In [22]:
import numpy as np


X = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
], dtype=np.float32) / 10.0


y = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=np.float32)


weights = np.random.uniform(-0.1, 0.1, size=15).astype(np.float32)


def get_terms(x):
    x1, x2, x3, x4 = x
    return np.array([
        1,
        x1, x2, x3, x4,
        x1*x1, x2*x2, x3*x3, x4*x4,
        x1*x2, x1*x3, x1*x4,
        x2*x3, x2*x4, x3*x4
    ], dtype=np.float32)


for _ in range(10000):
    for i in range(len(X)):
        terms = get_terms(X[i])
        prediction = np.dot(terms, weights)
        error = prediction - y[i]
        weights -= 0.1 * error * terms


print("Результаты:")
for i in range(len(X)):
    terms = get_terms(X[i])
    prediction = np.dot(terms, weights)
    print(f"{X[i] * 10} -> {prediction:.4f} (Истинное: {y[i]})")

Результаты:
[5. 2. 1. 0.] -> -0.1678 (Истинное: 0.0)
[6. 3. 2. 1.] -> 0.1499 (Истинное: 0.0)
[4. 1. 1. 0.] -> 0.0865 (Истинное: 0.0)
[7. 4. 6. 3.] -> 1.0844 (Истинное: 1.0)
[8. 5. 5. 4.] -> 1.0087 (Истинное: 1.0)
[6. 3. 4. 2.] -> 0.9013 (Истинное: 1.0)
[3. 8. 7. 9.] -> 1.0118 (Истинное: 1.0)
[4. 9. 8. 8.] -> -0.0003 (Истинное: 0.0)
[2. 7. 6. 7.] -> 0.9969 (Истинное: 1.0)
