<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Данные (X нормирован, Y — один выход 0 или 1)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
], dtype=np.float32) / 10.0  # Нормализация

# Простые бинарные метки (0 или 1)
y_train = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=np.float32)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)

# Инициализация весового вектора (5 членов линейного полинома: 1, x1, x2, x3, x4)
weights = np.random.uniform(-0.1, 0.1, size=5).astype(np.float32)

print("\nНачальные веса:")
print(weights)
print("\n")

learning_rate = 0.1
epochs = 10000

def compute_linear(x):
    x1, x2, x3, x4 = x
    terms = np.array([1, x1, x2, x3, x4], dtype=np.float32)
    return np.dot(terms, weights)

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход: получаем выход
        prediction = compute_linear(x)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        gradients_terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)

        # Обновление весов
        weights -= learning_rate * error * gradients_terms

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

print("\nОбученные веса:")
print(weights)

# Проверка
print("\nРезультаты:")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_linear(x)
    print(f"{x*10} -> {pred:.4f} (Истинное: {y_train[i]})")

X_train:
[[0.5 0.2 0.1 0. ]
 [0.6 0.3 0.2 0.1]
 [0.4 0.1 0.1 0. ]
 [0.7 0.4 0.6 0.3]
 [0.8 0.5 0.5 0.4]
 [0.6 0.3 0.4 0.2]
 [0.3 0.8 0.7 0.9]
 [0.4 0.9 0.8 0.8]
 [0.2 0.7 0.6 0.7]
 [0.5 0.6 0.5 0.6]]

y_train:
[0. 0. 0. 1. 1. 1. 1. 0. 1. 0.]

Начальные веса:
[ 0.08959855 -0.04593083  0.05601776  0.05222572  0.04004857]


Эпоха 0, Ошибка: 3.1090426445007324
Эпоха 500, Ошибка: 1.5120575428009033
Эпоха 1000, Ошибка: 1.390214204788208
Эпоха 1500, Ошибка: 1.36503005027771
Эпоха 2000, Ошибка: 1.3587838411331177
Эпоха 2500, Ошибка: 1.356945514678955
Эпоха 3000, Ошибка: 1.3563134670257568
Эпоха 3500, Ошибка: 1.3560714721679688
Эпоха 4000, Ошибка: 1.3559726476669312
Эпоха 4500, Ошибка: 1.3559316396713257
Эпоха 5000, Ошибка: 1.355914831161499
Эпоха 5500, Ошибка: 1.3559068441390991
Эпоха 6000, Ошибка: 1.3559050559997559
Эпоха 6500, Ошибка: 1.3559050559997559
Эпоха 7000, Ошибка: 1.3559050559997559
Эпоха 7500, Ошибка: 1.3559050559997559
Эпоха 8000, Ошибка: 1.3559050559997559
Эпоха 8500, Ошибка: 1.3