<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Данные (X нормирован, Y — один выход 0 или 1)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
], dtype=np.float32) / 10.0  # Нормализация

y_train = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=np.float32)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)

# Инициализация весов (5 членов: 1, x1, x2, x3, x4)
weights = np.random.uniform(-0.1, 0.1, size=5).astype(np.float32)

print("\nНачальные веса:")
print(weights)
print("\n")

learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Вычисление линейного полинома: prediction = w0 + w1*x1 + w2*x2 + w3*x3 + w4*x4
        terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
        prediction = np.dot(terms, weights)
        error = prediction - target
        total_error += error ** 2

        # Градиенты для каждого веса (производные по w0, w1, w2, w3, w4)
        gradients = terms  # т.к. ∂(prediction)/∂w = term

        # Обновление весов
        weights -= learning_rate * error * gradients

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

print("\nОбученные веса:")
print(weights)

# Проверка
print("\nРезультаты:")
for i in range(len(X_train)):
    x = X_train[i]
    terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
    pred = np.dot(terms, weights)
    print(f"{x * 10} -> {pred:.4f} (Истинное: {y_train[i]})")

X_train:
[[0.5 0.2 0.1 0. ]
 [0.6 0.3 0.2 0.1]
 [0.4 0.1 0.1 0. ]
 [0.7 0.4 0.6 0.3]
 [0.8 0.5 0.5 0.4]
 [0.6 0.3 0.4 0.2]
 [0.3 0.8 0.7 0.9]
 [0.4 0.9 0.8 0.8]
 [0.2 0.7 0.6 0.7]
 [0.5 0.6 0.5 0.6]]

y_train:
[0. 0. 0. 1. 1. 1. 1. 0. 1. 0.]

Начальные веса:
[-0.06498353 -0.01739916  0.06963526  0.0687026   0.05796387]


Эпоха 0, Ошибка: 3.3627219200134277
Эпоха 500, Ошибка: 1.5125329494476318
Эпоха 1000, Ошибка: 1.3902866840362549
Эпоха 1500, Ошибка: 1.3650482892990112
Эпоха 2000, Ошибка: 1.3587884902954102
Эпоха 2500, Ошибка: 1.3569473028182983
Эпоха 3000, Ошибка: 1.3563144207000732
Эпоха 3500, Ошибка: 1.3560714721679688
Эпоха 4000, Ошибка: 1.3559730052947998
Эпоха 4500, Ошибка: 1.3559322357177734
Эпоха 5000, Ошибка: 1.35591459274292
Эпоха 5500, Ошибка: 1.3559068441390991
Эпоха 6000, Ошибка: 1.3559050559997559
Эпоха 6500, Ошибка: 1.3559050559997559
Эпоха 7000, Ошибка: 1.3559050559997559
Эпоха 7500, Ошибка: 1.3559050559997559
Эпоха 8000, Ошибка: 1.3559050559997559
Эпоха 8500, Ошибка: 