<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_x_y.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import numpy as np
import random

# Данные (X нормирован, Y — один выход 0 или 1)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
], dtype=np.float32) / 10.0  # Нормализация

# Простые бинарные метки (0 или 1)
y_train = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=np.float32)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)

# Инициализация весового вектора (20 членов полинома × 1 выход)
weights = np.random.uniform(-0.1, 0.1, size=(20, 1)).astype(np.float32)

print("\nНачальные веса:")
print(weights)
print("\n")

learning_rate = 0.1
epochs = 10000

def compute_polynomial(x, coeffs):
    x1, x2, x3, x4 = x
    terms = np.array([
        1,          # Константа
        x1, x2, x3, x4,
        x1*x1, x2*x2, x3*x3, x4*x4,
        x1*x2, x1*x3, x1*x4,
        x2*x3, x2*x4, x3*x4,
        x1*x2*x3, x1*x2*x4, x1*x3*x4, x2*x3*x4,
        x1*x2*x3*x4
    ], dtype=np.float32)
    return np.dot(terms, coeffs)  # Умножение terms (20,) на coeffs (20,1) -> скаляр

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход: получаем выход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients_terms = np.array([
            1, x1, x2, x3, x4,
            x1*x1, x2*x2, x3*x3, x4*x4,
            x1*x2, x1*x3, x1*x4,
            x2*x3, x2*x4, x3*x4,
            x1*x2*x3, x1*x2*x4, x1*x3*x4, x2*x3*x4,
            x1*x2*x3*x4
        ], dtype=np.float32)

        # Обновление весов
        weights -= learning_rate * (error * gradients_terms.reshape(-1, 1))

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

print("\nОбученные веса:")
print(weights)

# Проверка
print("\nРезультаты:")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial_vector(x, weights)
    print(f"{x*10} -> {pred} (Истинное: {y_train[i]})")

X_train:
[[0.5 0.2 0.1 0. ]
 [0.6 0.3 0.2 0.1]
 [0.4 0.1 0.1 0. ]
 [0.7 0.4 0.6 0.3]
 [0.8 0.5 0.5 0.4]
 [0.6 0.3 0.4 0.2]
 [0.3 0.8 0.7 0.9]
 [0.4 0.9 0.8 0.8]
 [0.2 0.7 0.6 0.7]
 [0.5 0.6 0.5 0.6]]

y_train:
[0. 0. 0. 1. 1. 1. 1. 0. 1. 0.]

Начальные веса:
[[-0.03311976]
 [-0.02108554]
 [ 0.00598812]
 [-0.06772653]
 [ 0.01439918]
 [ 0.06108646]
 [ 0.05203219]
 [-0.06922002]
 [-0.07015011]
 [-0.04636513]
 [-0.02778506]
 [-0.01830888]
 [ 0.03593944]
 [-0.08866391]
 [-0.09306546]
 [-0.02161789]
 [ 0.03943274]
 [-0.06131293]
 [ 0.0283009 ]
 [-0.04803437]]


Эпоха 0, Ошибка: [4.193833]
Эпоха 500, Ошибка: [0.40470833]
Эпоха 1000, Ошибка: [0.28809157]
Эпоха 1500, Ошибка: [0.24139288]
Эпоха 2000, Ошибка: [0.21156602]
Эпоха 2500, Ошибка: [0.19021556]
Эпоха 3000, Ошибка: [0.17439309]
Эпоха 3500, Ошибка: [0.1624082]
Эпоха 4000, Ошибка: [0.15313971]
Эпоха 4500, Ошибка: [0.1458207]
Эпоха 5000, Ошибка: [0.1399198]
Эпоха 5500, Ошибка: [0.135068]
Эпоха 6000, Ошибка: [0.1310071]
Эпоха 6500, Ошибка: [

In [84]:
import numpy as np
import random

# Данные (X нормирован, Y — 3 выхода)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
], dtype=np.float32) / 10.0  # Нормализация

y_train = np.array([
    [0, 1, 0], [0, 1, 1], [0, 1, 1],
    [1, 0, 1], [1, 0, 1], [1, 0, 1],
    [1, 1, 1], [0, 0, 1], [1, 0, 1],
    [0, 1, 0]
], dtype=np.float32)

# Функции для разных моделей полиномов
def linear_terms(x):
    x1, x2, x3, x4 = x
    return np.array([
        1,          # Константа
        x1, x2, x3, x4
    ], dtype=np.float32)  # 5 членов

def quadratic_terms(x):
    x1, x2, x3, x4 = x
    terms = linear_terms(x)
    quadratic = np.array([
        x1*x1, x2*x2, x3*x3, x4*x4,
        x1*x2, x1*x3, x1*x4,
        x2*x3, x2*x4, x3*x4
    ], dtype=np.float32)
    return np.concatenate([terms, quadratic])  # 5 + 10 = 15 членов

def cubic_terms(x):
    x1, x2, x3, x4 = x
    terms = quadratic_terms(x)
    cubic = np.array([
        # Все возможные кубические члены (20 штук)
        x1*x1*x1, x2*x2*x2, x3*x3*x3, x4*x4*x4,  # Кубы переменных
        x1*x1*x2, x1*x1*x3, x1*x1*x4,            # x1² с другими
        x2*x2*x1, x2*x2*x3, x2*x2*x4,            # x2² с другими
        x3*x3*x1, x3*x3*x2, x3*x3*x4,            # x3² с другими
        x4*x4*x1, x4*x4*x2, x4*x4*x3,            # x4² с другими
        x1*x2*x3, x1*x2*x4, x1*x3*x4, x2*x3*x4   # Смешанные тройные
    ], dtype=np.float32)
    return np.concatenate([terms, cubic])  # 15 + 20 = 35 членов

def quartic_terms(x):
    x1, x2, x3, x4 = x
    terms = cubic_terms(x)
    quartic = np.array([
        # Все возможные члены 4-й степени (35 штук)
        x1*x1*x1*x1, x2*x2*x2*x2, x3*x3*x3*x3, x4*x4*x4*x4,  # x^4
        x1*x1*x1*x2, x1*x1*x1*x3, x1*x1*x1*x4,               # x1³ с другими
        x2*x2*x2*x1, x2*x2*x2*x3, x2*x2*x2*x4,               # x2³ с другими
        x3*x3*x3*x1, x3*x3*x3*x2, x3*x3*x3*x4,               # x3³ с другими
        x4*x4*x4*x1, x4*x4*x4*x2, x4*x4*x4*x3,               # x4³ с другими
        x1*x1*x2*x2, x1*x1*x3*x3, x1*x1*x4*x4,               # x1²x2² и т.д.
        x2*x2*x3*x3, x2*x2*x4*x4, x3*x3*x4*x4,
        x1*x1*x2*x3, x1*x1*x2*x4, x1*x1*x3*x4,               # x1² с двумя другими
        x2*x2*x1*x3, x2*x2*x1*x4, x2*x2*x3*x4,
        x3*x3*x1*x2, x3*x3*x1*x4, x3*x3*x2*x4,
        x4*x4*x1*x2, x4*x4*x1*x3, x4*x4*x2*x3,
        x1*x2*x3*x4  # Все 4 переменные
    ], dtype=np.float32)
    return np.concatenate([terms, quartic])  # 35 + 35 = 70 членов

# Проверка количества членов
print(f"Проверка размеров:")
print(f"Линейная: {len(linear_terms(X_train[0]))}")  # 5
print(f"Квадратичная: {len(quadratic_terms(X_train[0]))}")  # 15
print(f"Кубическая: {len(cubic_terms(X_train[0]))}")  # 35
print(f"Четвертой степени: {len(quartic_terms(X_train[0]))}")  # 70

# Перебор моделей разной сложности
models = [
    ("Линейная модель", linear_terms, 5),
    ("Квадратичная модель", quadratic_terms, 15),
    ("Кубическая модель", cubic_terms, 35),
    ("Полином 4-й степени", quartic_terms, 70)
]

for model_name, term_func, num_terms in models:
    print(f"\n=== {model_name} (членов: {num_terms}) ===")

    # Инициализация весов
    weights = np.random.uniform(-0.1, 0.1, size=(num_terms, 3)).astype(np.float32)

    learning_rate = 0.1
    epochs = 10000

    def compute_polynomial(x, coeffs):
        terms = term_func(x)
        return np.dot(terms, coeffs)

    # Обучение
    for epoch in range(epochs):
        total_error = 0
        for i in range(len(X_train)):
            x = X_train[i]
            target = y_train[i]

            prediction = compute_polynomial(x, weights)
            error = prediction - target
            total_error += np.sum(error**2)

            gradients_terms = term_func(x)

            for j in range(3):
                weights[:, j] -= learning_rate * (error[j] * gradients_terms)

        if epoch % 500 == 0:
            print(f"Эпоха {epoch}, Ошибка: {total_error:.4f}")

    # Проверка
    print("\nРезультаты:")
    for i in range(len(X_train)):
        x = X_train[i]
        pred = compute_polynomial(x, weights)
        print(f"{x*10} -> [{pred[0]:.2f}, {pred[1]:.2f}, {pred[2]:.2f}] (Истинное: {y_train[i]})")

    # Вывод ошибки на обучающей выборке
    final_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]
        pred = compute_polynomial(x, weights)
        final_error += np.sum((pred - target)**2)
    print(f"\nФинальная ошибка: {final_error:.4f}")

Проверка размеров:
Линейная: 5
Квадратичная: 15
Кубическая: 35
Четвертой степени: 70

=== Линейная модель (членов: 5) ===
Эпоха 0, Ошибка: 11.1366
Эпоха 500, Ошибка: 3.9386
Эпоха 1000, Ошибка: 3.7707
Эпоха 1500, Ошибка: 3.7437
Эпоха 2000, Ошибка: 3.7383
Эпоха 2500, Ошибка: 3.7371
Эпоха 3000, Ошибка: 3.7368
Эпоха 3500, Ошибка: 3.7368
Эпоха 4000, Ошибка: 3.7367
Эпоха 4500, Ошибка: 3.7367
Эпоха 5000, Ошибка: 3.7367
Эпоха 5500, Ошибка: 3.7367
Эпоха 6000, Ошибка: 3.7367
Эпоха 6500, Ошибка: 3.7367
Эпоха 7000, Ошибка: 3.7367
Эпоха 7500, Ошибка: 3.7367
Эпоха 8000, Ошибка: 3.7367
Эпоха 8500, Ошибка: 3.7367
Эпоха 9000, Ошибка: 3.7367
Эпоха 9500, Ошибка: 3.7367

Результаты:
[5. 2. 1. 0.] -> [-0.16, 0.90, 0.58] (Истинное: [0. 1. 0.])
[6. 3. 2. 1.] -> [-0.09, 0.76, 0.56] (Истинное: [0. 1. 1.])
[4. 1. 1. 0.] -> [0.35, 0.96, 0.72] (Истинное: [0. 1. 1.])
[7. 4. 6. 3.] -> [1.15, -0.38, 1.17] (Истинное: [1. 0. 1.])
[8. 5. 5. 4.] -> [0.62, 0.39, 0.67] (Истинное: [1. 0. 1.])
[6. 3. 4. 2.] -> [0.78, 0.22, 