<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Данные (X нормирован, Y — один выход 0 или 1)
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
], dtype=np.float32) / 10.0  # Нормализация

y_train = np.array([0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=np.float32)

print("X_train:")
print(X_train)
print("\ny_train:")
print(y_train)

# Инициализация весов (5 членов: 1, x1, x2, x3, x4)
weights = np.random.uniform(-0.1, 0.1, size=5).astype(np.float32)

print("\nНачальные веса:")
print(weights)
print("\n")

learning_rate = 0.1
epochs = 10000

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Вычисление линейного полинома: prediction = w0 + w1*x1 + w2*x2 + w3*x3 + w4*x4
        terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
        prediction = np.dot(terms, weights)
        error = prediction - target
        total_error += error ** 2

        # Обновление весов
        weights -= learning_rate * error * terms

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

print("\nОбученные веса:")
print(weights)

# Проверка
print("\nРезультаты:")
for i in range(len(X_train)):
    x = X_train[i]
    terms = np.array([1, x[0], x[1], x[2], x[3]], dtype=np.float32)
    pred = np.dot(terms, weights)
    print(f"{x * 10} -> {pred:.4f} (Истинное: {y_train[i]})")

X_train:
[[0.5 0.2 0.1 0. ]
 [0.6 0.3 0.2 0.1]
 [0.4 0.1 0.1 0. ]
 [0.7 0.4 0.6 0.3]
 [0.8 0.5 0.5 0.4]
 [0.6 0.3 0.4 0.2]
 [0.3 0.8 0.7 0.9]
 [0.4 0.9 0.8 0.8]
 [0.2 0.7 0.6 0.7]]

y_train:
[0. 0. 0. 1. 1. 1. 1. 0. 1.]

Начальные веса:
[ 0.08647399  0.07661039  0.06489561 -0.017115   -0.05278393]


Эпоха 0, Ошибка: 2.8374757766723633
Эпоха 500, Ошибка: 0.9802885055541992
Эпоха 1000, Ошибка: 0.7728320360183716
Эпоха 1500, Ошибка: 0.7184216976165771
Эпоха 2000, Ошибка: 0.7021446824073792
Эпоха 2500, Ошибка: 0.6966232657432556
Эпоха 3000, Ошибка: 0.6945061683654785
Эпоха 3500, Ошибка: 0.693612813949585
Эпоха 4000, Ошибка: 0.6932108402252197
Эпоха 4500, Ошибка: 0.6930248737335205
Эпоха 5000, Ошибка: 0.6929363012313843
Эпоха 5500, Ошибка: 0.6928945779800415
Эпоха 6000, Ошибка: 0.6928736567497253
Эпоха 6500, Ошибка: 0.6928638815879822
Эпоха 7000, Ошибка: 0.6928602457046509
Эпоха 7500, Ошибка: 0.6928602457046509
Эпоха 8000, Ошибка: 0.6928602457046509
Эпоха 8500, Ошибка: 0.6928602457046509
Эп