<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/polinomial_integer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import random

# Нормализуем данные (масштабируем к [0, 1])
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
], dtype=np.float32)
X_train = X_train / 10.0  # Нормализуем, деля на максимальное значение (9)

y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2], dtype=np.float32)

# Инициализация весов (меньший диапазон)
weights = np.array([random.uniform(-0.1, 0.1) for _ in range(20)], dtype=np.float32)
learning_rate = 0.001  # Уменьшенный learning rate
epochs = 10000
lambda_reg = 0.01  # Коэффициент регуляризации

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода"""
    x1, x2, x3, x4 = x
    return (
        coeffs[0] +  # константа
        coeffs[1]*x1 + coeffs[2]*x2 + coeffs[3]*x3 + coeffs[4]*x4 +
        coeffs[5]*x1*x1 + coeffs[6]*x2*x2 + coeffs[7]*x3*x3 + coeffs[8]*x4*x4 +
        coeffs[9]*x1*x2 + coeffs[10]*x1*x3 + coeffs[11]*x1*x4 +
        coeffs[12]*x2*x3 + coeffs[13]*x2*x4 + coeffs[14]*x3*x4 +
        coeffs[15]*x1*x2*x3 + coeffs[16]*x1*x2*x4 +
        coeffs[17]*x1*x3*x4 + coeffs[18]*x2*x3*x4 +
        coeffs[19]*x1*x2*x3*x4
    )

for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i]

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома
        x1, x2, x3, x4 = x
        gradients = np.array([
            1,              # w0 (константа)
            x1,             # w1
            x2,             # w2
            x3,             # w3
            x4,             # w4
            x1*x1,          # w5 (x1^2)
            x2*x2,          # w6 (x2^2)
            x3*x3,          # w7 (x3^2)
            x4*x4,          # w8 (x4^2)
            x1*x2,          # w9
            x1*x3,          # w10
            x1*x4,          # w11
            x2*x3,          # w12
            x2*x4,          # w13
            x3*x4,          # w14
            x1*x2*x3,       # w15
            x1*x2*x4,       # w16
            x1*x3*x4,       # w17
            x2*x3*x4,       # w18
            x1*x2*x3*x4     # w19
        ], dtype=np.float32)

        # Обновление весов с L2 регуляризацией
        weights -= learning_rate * (error * gradients + lambda_reg * weights)

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x*10} -> {pred:.2f} ({y_train[i]})")

# Вывод уравнения
print("\nУравнение с квадратными членами:")
print(f"y = {weights[0]:.4f} + {weights[1]:.4f}*x1 + {weights[2]:.4f}*x2 + {weights[3]:.4f}*x3 + {weights[4]:.4f}*x4 +")
print(f"     {weights[5]:.4f}*x1^2 + {weights[6]:.4f}*x2^2 + {weights[7]:.4f}*x3^2 + {weights[8]:.4f}*x4^2 +")
print(f"     {weights[9]:.4f}*x1*x2 + {weights[10]:.4f}*x1*x3 + {weights[11]:.4f}*x1*x4 + {weights[12]:.4f}*x2*x3 + {weights[13]:.4f}*x2*x4 + {weights[14]:.4f}*x3*x4 +")
print(f"     {weights[15]:.4f}*x1*x2*x3 + {weights[16]:.4f}*x1*x2*x4 + {weights[17]:.4f}*x1*x3*x4 + {weights[18]:.4f}*x2*x3*x4 +")
print(f"     {weights[19]:.4f}*x1*x2*x3*x4")

Эпоха 0, Ошибка: 17.401718139648438
Эпоха 500, Ошибка: 1.0932121276855469
Эпоха 1000, Ошибка: 1.010514259338379
Эпоха 1500, Ошибка: 0.9618918895721436
Эпоха 2000, Ошибка: 0.920678436756134
Эпоха 2500, Ошибка: 0.8846067190170288
Эпоха 3000, Ошибка: 0.8527190685272217
Эпоха 3500, Ошибка: 0.824371874332428
Эпоха 4000, Ошибка: 0.7990723848342896
Эпоха 4500, Ошибка: 0.7764222025871277
Эпоха 5000, Ошибка: 0.7560900449752808
Эпоха 5500, Ошибка: 0.737800121307373
Эпоха 6000, Ошибка: 0.7213144302368164
Эпоха 6500, Ошибка: 0.7064258456230164
Эпоха 7000, Ошибка: 0.6929638385772705
Эпоха 7500, Ошибка: 0.6807664632797241
Эпоха 8000, Ошибка: 0.6697016954421997
Эпоха 8500, Ошибка: 0.6596542596817017
Эпоха 9000, Ошибка: 0.6505178809165955
Эпоха 9500, Ошибка: 0.6421947479248047

Результаты:
Вход -> Предсказание (Истинное значение)
[5. 2. 1. 0.] -> 0.11 (0.0)
[6. 3. 2. 1.] -> 0.34 (0.0)
[4. 1. 1. 0.] -> 0.10 (0.0)
[7. 4. 6. 3.] -> 1.03 (1.0)
[8. 5. 5. 4.] -> 1.10 (1.0)
[6. 3. 4. 2.] -> 0.67 (1.0)
[3. 8.

In [26]:
import numpy as np
import random

# Масштабируем данные, умножив на 10 и преобразовав в целые
X_train = np.array([
    [5, 2, 1, 0], [6, 3, 2, 1], [4, 1, 1, 0],
    [7, 4, 6, 3], [8, 5, 5, 4], [6, 3, 4, 2],
    [3, 8, 7, 9], [4, 9, 8, 8], [2, 7, 6, 7],
    [5, 6, 5, 6]
])
y_train = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])

# Инициализируем веса как целые числа в диапазоне [-100, 100]
weights = [random.randint(-100, 100) for _ in range(20)]

# Используем целочисленный learning rate (умноженный на 1000 для сохранения точности)
learning_rate = 10  # Фактически 0.01, но мы будем делить на 1000 позже
epochs = 10000

def compute_polynomial(x, coeffs):
    """Вычисляет значение полинома для одного выхода (с масштабированием)"""
    x1, x2, x3, x4 = x
    # Все вычисления производятся в целых числах, затем делим на 100000 для масштабирования
    return (
        coeffs[0]*1000 +  # константа (умножена на 1000)
        coeffs[1]*x1*10 + coeffs[2]*x2*10 + coeffs[3]*x3*10 + coeffs[4]*x4*10 +
        coeffs[5]*x1*x1 + coeffs[6]*x2*x2 + coeffs[7]*x3*x3 + coeffs[8]*x4*x4 +
        coeffs[9]*x1*x2 + coeffs[10]*x1*x3 + coeffs[11]*x1*x4 +
        coeffs[12]*x2*x3 + coeffs[13]*x2*x4 + coeffs[14]*x3*x4 +
        coeffs[15]*x1*x2*x3//10 + coeffs[16]*x1*x2*x4//10 +
        coeffs[17]*x1*x3*x4//10 + coeffs[18]*x2*x3*x4//10 +
        coeffs[19]*x1*x2*x3*x4//100
    ) // 1000  # Деление для масштабирования

# Обучение с целыми числами
for epoch in range(epochs):
    total_error = 0
    for i in range(len(X_train)):
        x = X_train[i]
        target = y_train[i] * 1000  # Масштабируем target

        # Прямой проход
        prediction = compute_polynomial(x, weights)
        error = prediction - target
        total_error += error**2

        # Градиенты для каждого члена полинома (уже масштабированы)
        x1, x2, x3, x4 = x
        gradients = [
            1000,              # w0 (константа)
            x1*10,              # w1
            x2*10,              # w2
            x3*10,              # w3
            x4*10,              # w4
            x1*x1,              # w5 (x1^2)
            x2*x2,              # w6 (x2^2)
            x3*x3,              # w7 (x3^2)
            x4*x4,              # w8 (x4^2)
            x1*x2,              # w9
            x1*x3,              # w10
            x1*x4,              # w11
            x2*x3,              # w12
            x2*x4,              # w13
            x3*x4,              # w14
            x1*x2*x3//10,       # w15
            x1*x2*x4//10,       # w16
            x1*x3*x4//10,       # w17
            x2*x3*x4//10,       # w18
            x1*x2*x3*x4//100    # w19
        ]

        for k in range(len(weights)):
            # Обновление весов с целочисленным learning rate
            update = (error * gradients[k]) // 1000  # learning_rate = 10/1000
            weights[k] -= update

    if epoch % 500 == 0:
        print(f"Эпоха {epoch}, Ошибка: {total_error}")

# Проверка
print("\nРезультаты:")
print("Вход -> Предсказание (Истинное значение)")
for i in range(len(X_train)):
    x = X_train[i]
    pred = compute_polynomial(x, weights)
    print(f"{x} -> {pred} ({y_train[i]})")

# Вывод уравнения (с масштабированными коэффициентами)
print("\nУравнение с квадратными членами (масштабированное):")
print(f"y = [({weights[0]}*1000 + {weights[1]}*x1*10 + {weights[2]}*x2*10 + {weights[3]}*x3*10 + {weights[4]}*x4*10 +")
print(f"     {weights[5]}*x1^2 + {weights[6]}*x2^2 + {weights[7]}*x3^2 + {weights[8]}*x4^2 +")
print(f"     {weights[9]}*x1*x2 + {weights[10]}*x1*x3 + {weights[11]}*x1*x4 + {weights[12]}*x2*x3 + {weights[13]}*x2*x4 + {weights[14]}*x3*x4 +")
print(f"     {weights[15]}*x1*x2*x3//10 + {weights[16]}*x1*x2*x4//10 + {weights[17]}*x1*x3*x4//10 + {weights[18]}*x2*x3*x4//10 +")
print(f"     {weights[19]}*x1*x2*x3*x4//100) // 1000]")

Эпоха 0, Ошибка: 1971660
Эпоха 500, Ошибка: 1499134
Эпоха 1000, Ошибка: 1122428
Эпоха 1500, Ошибка: 861134
Эпоха 2000, Ошибка: 711867
Эпоха 2500, Ошибка: 597324
Эпоха 3000, Ошибка: 544374
Эпоха 3500, Ошибка: 471162
Эпоха 4000, Ошибка: 453732
Эпоха 4500, Ошибка: 408344
Эпоха 5000, Ошибка: 412056
Эпоха 5500, Ошибка: 387718
Эпоха 6000, Ошибка: 409036
Эпоха 6500, Ошибка: 428804
Эпоха 7000, Ошибка: 423700
Эпоха 7500, Ошибка: 418490
Эпоха 8000, Ошибка: 422258
Эпоха 8500, Ошибка: 412164
Эпоха 9000, Ошибка: 423632
Эпоха 9500, Ошибка: 447676

Результаты:
Вход -> Предсказание (Истинное значение)
[5 2 1 0] -> -101 (0)
[6 3 2 1] -> 199 (0)
[4 1 1 0] -> 187 (0)
[7 4 6 3] -> 1489 (1)
[8 5 5 4] -> 1445 (1)
[6 3 4 2] -> 957 (1)
[3 8 7 9] -> 1945 (2)
[4 9 8 8] -> 2036 (2)
[2 7 6 7] -> 1922 (2)
[5 6 5 6] -> 1998 (2)

Уравнение с квадратными членами (масштабированное):
y = [(867*1000 + -18355*x1*10 + -5524*x2*10 + 17972*x3*10 + 24838*x4*10 +
     -6631*x1^2 + -331*x2^2 + -8052*x3^2 + -9469*x4^2 +
     -2