<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/queens.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import numpy as np

a = np.zeros((3,3))

a[0,0] = 1
a[1,2] = 1

print(a)
print('------------')

queens = [(0,0), (1,2)]

def is_attacking(q1: tuple, q2: tuple):
    x1, y1 = map(int, q1)
    x2, y2 = map(int, q2)
    if (x1 == x2) or (y1 == y2) or (abs(x1 - x2) == abs(y1 - y2)):
        print(True)
    else:
        print(False)

def check_queens(queens: list):
    for i in range(len(queens)-1):
        for j in range(i+1, len(queens)):
            is_attacking(queens[i], queens[j])

check_queens(queens)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
------------
False
