<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/rbf_matrixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [199]:
import numpy as np
from scipy.interpolate import RBFInterpolator


X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([0, 1, 1, 0])


epsilon = 10

rbfi = RBFInterpolator(X, Y, kernel='gaussian', epsilon=epsilon)

print(rbfi([X[0]]))
print(rbfi([X[1]]))
print(rbfi([X[2]]))
print(rbfi([X[3]]))
print(rbfi(X))

[0.]
[1.]
[1.]
[0.]
[0. 1. 1. 0.]


In [204]:
import numpy as np

# Генерация данных XOR
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 1, 1, 0])

# Функция радиальной базисной функции
def rbf(x, c, sigma):
    """
    Вычисляет значение радиальной базисной функции (RBF) для двух точек.

    Аргументы:
        x: Первый вектор.
        c: Второй вектор (центр).
        sigma: Параметр ширины гауссовой функции.

    Возвращает:
        Значение RBF.
    """
    return np.exp(-np.linalg.norm(x - c)**2 / (2 * sigma**2))

# Создание матрицы фич
def create_feature_matrix(X, centers, sigma):
    """
    Создает матрицу фич, преобразуя исходные данные в пространство более высокой размерности.

    Аргументы:
        X: Исходные данные.
        centers: Центры RBF-ядер.
        sigma: Параметр ширины гауссовой функции.

    Возвращает:
        Матрица фич.
    """
    phi = np.empty((X.shape[0], centers.shape[0]))
    for i, x in enumerate(X):
        for j, c in enumerate(centers):
            phi[i, j] = rbf(x, c, sigma)
    return phi

# Обучение линейной модели
def train_linear_model(phi, y):
    """
    Обучает линейную модель методом псевдообратной матрицы.

    Аргументы:
        phi: Матрица фич.
        y: Целевые значения.

    Возвращает:
        Вектор весов модели.
    """
    return np.linalg.pinv(phi) @ y

# Предсказание
def predict(X_new, centers, sigma, weights):
    """
    Делает предсказания для новых данных.

    Аргументы:
        X_new: Новые данные.
        centers: Центры RBF-ядер.
        sigma: Параметр ширины гауссовой функции.
        weights: Вектор весов модели.

    Возвращает:
        Вектор предсказанных значений.
    """
    phi_new = create_feature_matrix(X_new, centers, sigma)
    return np.where(phi_new @ weights > 0.5, 1, 0)
    # return phi_new @ weights

# Параметры
num_centers = 5
sigma = 0.9
centers = np.random.rand(num_centers, 2)


# Создание матрицы фич
phi = create_feature_matrix(X, centers, sigma)

# Обучение модели
weights = train_linear_model(phi, y)

# Предсказание для одного образца
prediction_for_one = predict(X[[0]], centers, sigma, weights)
print(prediction_for_one)

prediction_for_one = predict(X[[1]], centers, sigma, weights)
print(prediction_for_one)

prediction_for_one = predict(X[[2]], centers, sigma, weights)
print(prediction_for_one)

prediction_for_one = predict(X[[3]], centers, sigma, weights)
print(prediction_for_one)

# Предсказание для нескольких образцов
prediction_for_many = predict(X, centers, sigma, weights)
print(prediction_for_many)

[0]
[1]
[1]
[0]
[0 1 1 0]


In [201]:
import numpy as np

A = np.array([[1, 3],
             [2, 4]])

A_pinv = np.linalg.pinv(A)
print(A_pinv)

print(A @ A_pinv)
print(A_pinv @ A)

print(np.where(A @ A_pinv > 0.5, 1, 0))
print(np.where(A_pinv @ A > 0.5, 1, 0))

[[-2.   1.5]
 [ 1.  -0.5]]
[[ 1.00000000e+00 -5.55111512e-16]
 [ 0.00000000e+00  1.00000000e+00]]
[[ 1.00000000e+00 -2.66453526e-15]
 [ 0.00000000e+00  1.00000000e+00]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
