<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/robot_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np
import random

m = 8
n = 8

# Создаем карту 14x14 из нулей
a = np.zeros((m, n))

# Добавляем границу из единиц
a[0, :] = 1          # Верхняя граница
a[-1, :] = 1         # Нижняя граница
a[:, 0] = 1          # Левый край
a[:, -1] = 1         # Правый край

# Функция для генерации препятствия заданного размера
def generate_obstacle(a, obstacle_height, obstacle_width):
    rows, cols = a.shape
    while True:
        start_row = random.randint(1, rows - obstacle_height - 1)
        start_col = random.randint(1, cols - obstacle_width - 1)

        # Проверяем, что место свободно
        if (a[start_row:start_row + obstacle_height, start_col:start_col + obstacle_width] == 0).all():
            a[start_row:start_row + obstacle_height, start_col:start_col + obstacle_width] = 1  # Заполняем препятствие
            break

# Генерируем случайные размеры препятствия от 2 до 6
obstacle_height = random.randint(1, 3)
obstacle_width = random.randint(1, 3)

# Генерируем случайные координаты для препятствия
generate_obstacle(a, obstacle_height, obstacle_width)

# Функция для заполнения карты числами
def fill_map(a):
    value = 2
    rows, cols = a.shape

    # Начнем с первой пустой клетки (0)
    for i in range(1, rows-1):
        for j in range(1, cols-1):
            if a[i, j] == 0:
                stack = [(i, j)]  # Используем стек для обхода
                while stack:
                    x, y = stack.pop()
                    if a[x, y] == 0:  # Если клетка пустая
                        a[x, y] = value
                        value += 1

                        # Добавляем соседние клетки в стек
                        if x > 0: stack.append((x - 1, y))  # Вверх
                        if x < rows - 1: stack.append((x + 1, y))  # Вниз
                        if y > 0: stack.append((x, y - 1))  # Влево
                        if y < cols - 1: stack.append((x, y + 1))  # Вправо

                break  # Заполнение завершено после первого найденного пустого места

# Функция для получения последовательности команд
def get_commands(a):
    commands = []
    rows, cols = a.shape

    # Начинаем с числа 2 и идем по всей матрице
    current_pos = None
    for i in range(rows):
        for j in range(cols):
            if a[i, j] == 2:
                current_pos = (i, j)
                break
        if current_pos is not None:
            break

    if current_pos is None:
        return commands  # Если нет числа 2 в матрице

    x, y = current_pos

    # Проходим по матрице и записываем команды
    while True:
        commands.append(f"({x}, {y})")  # Записываем текущую позицию

        # Проверяем соседние клетки на наличие следующего числа
        found_next = False
        for dx, dy, direction in [(-1, 0, 'вверх'), (1, 0, 'вниз'), (0, -1, 'влево'), (0, 1, 'вправо')]:
            nx, ny = x + dx, y + dy
            if 0 <= nx < rows and 0 <= ny < cols and a[nx, ny] == a[x, y] + 1:
                commands.append(direction)  # Записываем направление
                x, y = nx, ny
                found_next = True
                break

        if not found_next:
            break

    return commands

# Заполняем карту числами
fill_map(a)

# Получаем последовательность команд
command_sequence = get_commands(a)

# Печатаем карту и последовательность команд
print("Карта:")
print(a)
print("Последовательность команд:")
print(command_sequence)


Карта:
[[ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  2.  3.  4.  5.  6.  7.  1.]
 [ 1. 13. 12. 11. 10.  9.  8.  1.]
 [ 1. 14. 15. 16. 17. 18. 19.  1.]
 [ 1. 22. 21. 20.  1.  1.  1.  1.]
 [ 1. 23. 24. 25.  1.  1.  1.  1.]
 [ 1. 28. 27. 26.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]
Последовательность команд:
['(1, 1)', 'вправо', '(1, 2)', 'вправо', '(1, 3)', 'вправо', '(1, 4)', 'вправо', '(1, 5)', 'вправо', '(1, 6)', 'вниз', '(2, 6)', 'влево', '(2, 5)', 'влево', '(2, 4)', 'влево', '(2, 3)', 'влево', '(2, 2)', 'влево', '(2, 1)', 'вниз', '(3, 1)', 'вправо', '(3, 2)', 'вправо', '(3, 3)', 'вправо', '(3, 4)', 'вправо', '(3, 5)', 'вправо', '(3, 6)']
