<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/simple_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [228]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

training_inputs = np.array([[0,1], [1,0]])
training_outputs = np.array([[0,0],[1,1]])

weights = 2 * np.random.random((2,2)) - 1

for i in range(100):
    input_layer = training_inputs
    outputs = sigmoid(np.dot(input_layer, weights))
    error = training_outputs - outputs
    adjustments = np.dot(input_layer.T, error * (outputs))
    weights += 10*adjustments

print(weights)

print(sigmoid(np.dot(np.array([[0,1]]), weights)))
print(sigmoid(np.dot(np.array([[1,1]]), weights)))

[[ 6.92906415  6.92872926]
 [-3.83742239 -3.77367435]]
[[0.02109451 0.02245185]]
[[0.95654666 0.95910744]]
