<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/simple_sigmoid_xor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [309]:
import numpy as np


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def func1(epochs, X, y):
    input_neurons = 2
    hidden_neurons = 4
    output_neurons = 1
    weights_input_hidden = np.random.rand(input_neurons, hidden_neurons)
    weights_hidden_output = np.random.rand(hidden_neurons, output_neurons)
    for i in range(epochs):
        hidden_layer_input = np.dot(X, weights_input_hidden)
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
        output = sigmoid(output_layer_input)
        error = y - output
        output_gradient = output * (1 - output) * error
        error_hidden = output_gradient.dot(weights_hidden_output.T)
        hidden_gradient = hidden_layer_output * (1 - hidden_layer_output) * error_hidden
        weights_hidden_output += hidden_layer_output.T.dot(output_gradient)
        weights_input_hidden += X.T.dot(hidden_gradient)
    return weights_input_hidden, weights_hidden_output


def test1(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output


def find_best_coefficients1(X, y):
    best_error = np.inf
    global best_epoch
    for epoch in range(400, 500):
            weights_input_hidden, weights_hidden_output = func1(epoch, X, y)
            training_error = np.sum(np.square(y - test1(weights_input_hidden, weights_hidden_output, X)))
            if training_error < best_error:
                best_error = training_error
                best_epoch = epoch
    return best_epoch



X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])
y = np.array([[0], [1], [1], [0]])


epochs = find_best_coefficients1(X, y)
print("Best epoch:", epochs)

weights_input_hidden, weights_hidden_output = func1(epochs, X, y)

print(weights_input_hidden)
print(weights_hidden_output)

test_error = np.sum(np.square(y - test1(weights_input_hidden, weights_hidden_output, X)))
print("Test error:", "{:.5f}".format(test_error))

print("Predictions on test data:")
print(test1(weights_input_hidden, weights_hidden_output, np.array([[0, 0]])))
print(test1(weights_input_hidden, weights_hidden_output, np.array([[0, 1]])))
print(test1(weights_input_hidden, weights_hidden_output, np.array([[1, 0]])))
print(test1(weights_input_hidden, weights_hidden_output, np.array([[1, 1]])))

Best epoch: 498
[[ 1.62632537  1.52466988 -0.74795215  4.26288369]
 [-0.22204809 -0.15262591  2.46502903  4.20975282]]
[[-2.73213985]
 [-2.36369528]
 [-3.15347235]
 [ 6.14745037]]
Test error: 0.37492
Predictions on test data:
[[0.25904683]]
[[0.69935574]]
[[0.69523231]]
[[0.35291018]]


In [310]:
def func2(A, B, C, D, E, X, y):
    input_neurons = 2
    hidden_neurons = 4
    output_neurons = 1
    weights_input_hidden = A * np.random.rand(input_neurons, hidden_neurons) + B
    weights_hidden_output = C * np.random.rand(hidden_neurons, output_neurons) + D
    for i in range(epochs):
        hidden_layer_input = np.dot(X, weights_input_hidden)
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
        output = sigmoid(output_layer_input)
        error = y - output
        output_gradient = output * (1 - output) * error
        error_hidden = output_gradient.dot(weights_hidden_output.T)
        hidden_gradient = hidden_layer_output * (1 - hidden_layer_output) * error_hidden
        weights_hidden_output += E * hidden_layer_output.T.dot(output_gradient)
        weights_input_hidden += E * X.T.dot(hidden_gradient)
    return weights_input_hidden, weights_hidden_output


def test2(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output


def find_best_coefficients2(X, y):
    best_error = np.inf
    global best_A, best_B, best_C, best_D, best_E
    for A in range(1, 2):
        for B in range(1, 2):
            for C in range(1, 2):
                for D in range(1, 2):
                    for E in range(1, 10):
                        weights_input_hidden, weights_hidden_output = func2(A, B, C, D, E, X, y)
                        training_error = np.sum(np.square(y - test2(weights_input_hidden, weights_hidden_output, X)))
                        if training_error < best_error:
                            best_error = training_error
                            best_A, best_B, best_C, best_D, best_E = A, B, C, D, E
    return best_A, best_B, best_C, best_D, best_E


A, B, C, D, E = find_best_coefficients2(X, y)
print("Best coefficients:", A, B, C, D, E)

weights_input_hidden, weights_hidden_output = func2(A, B, C, D, E, X, y)

print(weights_input_hidden)
print(weights_hidden_output)

test_error = np.sum(np.square(y - test2(weights_input_hidden, weights_hidden_output, X)))
print("Test error:", "{:.5f}".format(test_error))

print("Predictions on test data:")
print(test2(weights_input_hidden, weights_hidden_output, np.array([[0, 0]])))
print(test2(weights_input_hidden, weights_hidden_output, np.array([[0, 1]])))
print(test2(weights_input_hidden, weights_hidden_output, np.array([[1, 0]])))
print(test2(weights_input_hidden, weights_hidden_output, np.array([[1, 1]])))

Best coefficients: 1 1 1 1 9
[[ 5.41295329 -2.61090017  7.17744061 -3.17727096]
 [ 5.16891293 -2.33616053 -3.39803959  6.69316872]]
[[12.58705942]
 [-3.3168822 ]
 [-8.33922952]
 [-8.30994563]]
Test error: 0.00252
Predictions on test data:
[[0.02437551]]
[[0.97476312]]
[[0.97438598]]
[[0.02509198]]


In [311]:
weights_input_hidden = np.array([[-2.36339103, 6.64933217, -2.86276887, 5.43549766], [3.78489417, -3.70050892, 5.04393831, 5.53390145]])
weights_hidden_output = np.array([[-4.49183793], [-9.48823949], [-5.69572417], [13.69858672]])

def simple_func_test(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output

print(simple_func_test(weights_input_hidden, weights_hidden_output, np.array([[0, 0]])))
print(simple_func_test(weights_input_hidden, weights_hidden_output, np.array([[0, 1]])))
print(simple_func_test(weights_input_hidden, weights_hidden_output, np.array([[1, 0]])))
print(simple_func_test(weights_input_hidden, weights_hidden_output, np.array([[1, 1]])))

[[0.04794321]]
[[0.9665782]]
[[0.96979629]]
[[0.01705977]]
