<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/simple_sigmoid_xor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [177]:
import numpy as np

def convert_to_bit_array(double_array):
    bit_array = []
    for sublist in double_array:
        binary_sublist = [int(bit) for num in sublist for bit in format(num, '08b')]
        bit_array.append(binary_sublist)
    return bit_array


X = [[14, 2, 80, 2, 16, 132, 115, 14],
     [3, 36, 25, 31, 4, 54, 45, 13],
     [11, 255, 11, 102, 54, 5, 255, 12],
     [171, 68, 2, 130, 6, 148, 35, 11]]


y = [[1, 0, 0, 0],
     [0, 1, 0, 1],
     [1, 0, 0, 0],
     [0, 1, 1, 0]]

X = np.array(convert_to_bit_array(X))
print(X)

[[0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
  0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0]
 [0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 1 1 0 0 0 0
  0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 1 0 1]
 [0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 1
  0 1 1 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0]
 [1 0 1 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0
  0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 1 1]]


In [184]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def func1(epochs, X, y):
    input_neurons = 64
    hidden_neurons = 4
    output_neurons = 4
    weights_input_hidden = np.random.rand(input_neurons, hidden_neurons)
    weights_hidden_output = np.random.rand(hidden_neurons, output_neurons)
    for i in range(epochs):
        hidden_layer_input = np.dot(X, weights_input_hidden)
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
        output = sigmoid(output_layer_input)
        error = y - output
        output_gradient = output * (1 - output) * error
        error_hidden = output_gradient.dot(weights_hidden_output.T)
        hidden_gradient = hidden_layer_output * (1 - hidden_layer_output) * error_hidden
        weights_hidden_output += hidden_layer_output.T.dot(output_gradient)
        weights_input_hidden += X.T.dot(hidden_gradient)
    return weights_input_hidden, weights_hidden_output


def test1(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output


def find_best_coefficients1(X, y):
    best_error = np.inf
    global best_epoch
    for epoch in range(1000, 1100):
            weights_input_hidden, weights_hidden_output = func1(epoch, X, y)
            training_error = np.sum(np.square(y - test1(weights_input_hidden, weights_hidden_output, X)))
            if training_error < best_error:
                best_error = training_error
                best_epoch = epoch
    return best_epoch


epochs = find_best_coefficients1(X, y)
print("Best epoch:", epochs)

weights_input_hidden, weights_hidden_output = func1(epochs, X, y)

print(weights_input_hidden)
print(weights_hidden_output)

test_error = np.sum(np.square(y - test1(weights_input_hidden, weights_hidden_output, X)))
print("Test error:", "{:.5f}".format(test_error))

print("Predictions on test data:")
print(test1(weights_input_hidden, weights_hidden_output, np.array([X[0]])))

Best epoch: 1026
[[ 0.77474465 -0.00276937  0.82761504  0.08793457]
 [ 0.31971196  0.51414791  0.73488002  0.39568391]
 [ 0.26329146  0.40742802  0.45691911  0.75546103]
 [ 0.55133225  0.57939913  0.61447668  0.99338848]
 [ 0.78191723  0.23407072  0.06421532  0.50952297]
 [ 0.35762139  0.58464597  1.01185599  0.16311933]
 [ 0.6943679   0.33163969  0.31391591  0.42519947]
 [ 0.26345229  0.04361985  0.5484533   0.91580786]
 [ 0.1847064   0.43911729  0.7397977   0.62683847]
 [ 0.78845523  0.69300556  0.09140256  0.83077649]
 [ 0.07276807  0.97259101  0.29548885  0.8158802 ]
 [ 0.4140043   0.52720916  0.63708752  0.48271353]
 [ 0.78760357  0.74331605  0.83968636  0.48255919]
 [ 0.52744914  0.86921328  0.84030644  0.83723571]
 [ 0.51141009  0.22924112  0.16814274  0.0085552 ]
 [ 0.81368591  0.25454833  0.64040019  0.09388282]
 [ 0.39764397  0.97670497  0.18341487  0.86020386]
 [ 0.19431845  0.40684981  0.50693639  0.79340664]
 [ 0.57660265  0.26049194  0.25746221  0.39766543]
 [ 0.7591264  

In [186]:
def func2(A, B, C, D, E, X, y):
    input_neurons = 64
    hidden_neurons = 4
    output_neurons = 4
    weights_input_hidden = A * np.random.rand(input_neurons, hidden_neurons) + B
    weights_hidden_output = C * np.random.rand(hidden_neurons, output_neurons) + D
    for i in range(epochs):
        hidden_layer_input = np.dot(X, weights_input_hidden)
        hidden_layer_output = sigmoid(hidden_layer_input)
        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
        output = sigmoid(output_layer_input)
        error = y - output
        output_gradient = output * (1 - output) * error
        error_hidden = output_gradient.dot(weights_hidden_output.T)
        hidden_gradient = hidden_layer_output * (1 - hidden_layer_output) * error_hidden
        weights_hidden_output += E * hidden_layer_output.T.dot(output_gradient)
        weights_input_hidden += E * X.T.dot(hidden_gradient)
    return weights_input_hidden, weights_hidden_output


def test2(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output


def find_best_coefficients2(X, y):
    best_error = np.inf
    global best_A, best_B, best_C, best_D, best_E
    for A in range(-1, 1):
        for B in range(-1, 1):
            for C in range(-1, 1):
                for D in range(-1, 1):
                    for E in range(1, 10):
                        weights_input_hidden, weights_hidden_output = func2(A, B, C, D, E, X, y)
                        training_error = np.sum(np.square(y - test2(weights_input_hidden, weights_hidden_output, X)))
                        if training_error < best_error:
                            best_error = training_error
                            best_A, best_B, best_C, best_D, best_E = A, B, C, D, E
    return best_A, best_B, best_C, best_D, best_E


A, B, C, D, E = find_best_coefficients2(X, y)
print("Best coefficients:", A, B, C, D, E)

weights_input_hidden, weights_hidden_output = func2(A, B, C, D, E, X, y)

print(weights_input_hidden)
print(weights_hidden_output)

test_error = np.sum(np.square(y - test2(weights_input_hidden, weights_hidden_output, X)))
print("Test error:", "{:.5f}".format(test_error))

print("Predictions on test data:")
print(test1(weights_input_hidden, weights_hidden_output, np.array([X[0]])))

Best coefficients: 0 0 -1 0 7
[[-0.32256005  0.73066405 -0.60075618 -0.42794735]
 [ 0.          0.          0.          0.        ]
 [-0.32256005  0.73066405 -0.60075618 -0.42794735]
 [ 0.          0.          0.          0.        ]
 [-0.60442233  0.25448778  0.39510117  0.34951912]
 [-0.1041976  -0.37386042  0.50656064  0.41059331]
 [-0.06106235 -0.14177054 -0.14256431 -0.10302674]
 [ 0.04313525  0.23208987 -0.64912495 -0.51362005]
 [-0.17766467 -0.10231586  0.48929672  0.36687316]
 [-0.50022473  0.62834819 -0.11145947 -0.06107419]
 [ 0.3656953  -0.49857418 -0.04836877 -0.08567269]
 [-0.17766467 -0.10231586  0.48929672  0.36687316]
 [-0.17766467 -0.10231586  0.48929672  0.36687316]
 [ 0.04313525  0.23208987 -0.64912495 -0.51362005]
 [-0.28186228 -0.47617627  0.99585736  0.77746648]
 [-0.17766467 -0.10231586  0.48929672  0.36687316]
 [ 0.          0.          0.          0.        ]
 [-0.1041976  -0.37386042  0.50656064  0.41059331]
 [ 0.          0.          0.          0.        ]
 

In [191]:
weights_input_hidden = np.array([[-0.32256005 ,  0.73066405, -0.60075618, -0.42794735],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.32256005,  0.73066405, -0.60075618, -0.42794735],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.60442233,  0.25448778,  0.39510117,  0.34951912],
                                  [-0.1041976 , -0.37386042,  0.50656064,  0.41059331],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [ 0.04313525,  0.23208987, -0.64912495, -0.51362005],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.50022473,  0.62834819, -0.11145947, -0.06107419],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [ 0.04313525,  0.23208987, -0.64912495, -0.51362005],
                                  [-0.28186228, -0.47617627,  0.99585736,  0.77746648],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.1041976 , -0.37386042,  0.50656064,  0.41059331],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.43916238, -0.77011874, -0.03110485, -0.04195255],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.50022473,  0.62834819, -0.11145947, -0.06107419],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [-0.32256005,  0.73066405, -0.60075618, -0.42794735],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [ 0.54335998, -0.39625832, -0.53766549, -0.45254586],
                                  [ 0.54335998, -0.39625832, -0.53766549, -0.45254586],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [ 0.54335998, -0.39625832, -0.53766549, -0.45254586],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.28186228, -0.47617627,  0.99585736,  0.77746648],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.04313525,  0.23208987, -0.64912495, -0.51362005],
                                  [-0.50022473,  0.62834819, -0.11145947, -0.06107419],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.42675765,  0.35680363, -0.09419554, -0.01735404],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.54335998, -0.39625832, -0.53766549, -0.45254586],
                                  [ 0.22079993,  0.33440573, -1.13842167, -0.88049321],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [ 0.54335998, -0.39625832, -0.53766549, -0.45254586],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.17766467, -0.10231586,  0.48929672,  0.36687316],
                                  [-0.28186228, -0.47617627,  0.99585736,  0.77746648],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [-0.28186228, -0.47617627,  0.99585736,  0.77746648],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [ 0.3656953 , -0.49857418, -0.04836877, -0.08567269],
                                  [-0.60442233,  0.25448778,  0.39510117,  0.34951912],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [ 0.        ,  0.        ,  0.        ,  0.        ],
                                  [-0.06106235, -0.14177054, -0.14256431, -0.10302674],
                                  [ 0.2614977 , -0.87243459,  0.45819187,  0.32492062],
                                  [-0.42675765,  0.35680363, -0.09419554, -0.01735404],
                                  [ 0.22079993,  0.33440573, -1.13842167, -0.88049321]])



weights_hidden_output = np.array([[-4.76324972,  4.76384157, -4.79867017,  4.76578645],
                                  [-4.72713796,  4.72875738,  4.85454124, -4.81940167],
                                  [ 3.92381651, -3.76753497, -3.48800084, -3.11138518],
                                  [ 2.02590725, -2.18856699, -1.792102,   -2.63666425]])


def simple_func_test(weights_input_hidden, weights_hidden_output, X):
    hidden_layer_input = np.dot(X, weights_input_hidden)
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
    output = sigmoid(output_layer_input)
    return output

print("Predictions on test data:")
print(test1(weights_input_hidden, weights_hidden_output, np.array([X[0]])))
print(test1(weights_input_hidden, weights_hidden_output, np.array([X[1]])))
print(test1(weights_input_hidden, weights_hidden_output, np.array([X[2]])))

Predictions on test data:
[[0.99629775 0.00368407 0.00470043 0.00377871]]
[[0.00853967 0.99146374 0.00834107 0.9912943 ]]
[[0.99660887 0.00337428 0.00456985 0.00373197]]
