<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/spiral_fiiling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
arr = np.zeros((6,6)) 
def spiralFill(arr, n): 
    cnt = 1
    for i in range(n): 
        for j in range(i, n-i): 
            arr[i][j] = cnt 
            cnt += 1
        for j in range(i+1, n-i): 
            arr[j][n-i-1] = cnt 
            cnt += 1
        for j in range(n-i-2, i-1, -1): 
            arr[n-i-1][j] = cnt 
            cnt += 1
        for j in range(n-i-2, i, -1): 
            arr[j][i] = cnt 
            cnt += 1

spiralFill(arr, 6) 
print(arr)

[[ 1.  2.  3.  4.  5.  6.]
 [20. 21. 22. 23. 24.  7.]
 [19. 32. 33. 34. 25.  8.]
 [18. 31. 36. 35. 26.  9.]
 [17. 30. 29. 28. 27. 10.]
 [16. 15. 14. 13. 12. 11.]]
