<a href="https://colab.research.google.com/github/InowaR/colab/blob/main/SVM_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [184]:
import random
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split


max_path_length = 15
center = (7, 7)
number_of_maps = 2500


def generate_map():
    game_map = [[0 for _ in range(max_path_length)] for _ in range(max_path_length)]
    game_map[center[0]][center[1]] = 2
    while True:
        x, y = random.randint(0, max_path_length-1), random.randint(0, max_path_length-1)
        if (x, y) != center:
            game_map[x][y] = 1
            break

    return game_map, (x, y)

def find_path(start, goal):
    path = []
    x, y = start
    gx, gy = goal

    while (x, y) != (gx, gy):
        if x < gx:
            path.append([0, 0])  # Движение вниз
            x += 1
        elif x > gx:
            path.append([1, 1])  # Движение вверх
            x -= 1

        if y < gy:
            path.append([0, 1])  # Движение вправо
            y += 1
        elif y > gy:
            path.append([1 ,0])  # Движение влево
            y -= 1

    return path

maps = []
paths = []


for _ in range(number_of_maps):
    game_map, goal = generate_map()
    maps.append(game_map)
    path = find_path(center, goal)
    paths.append(path)


for i in range(len(paths)):
    while len(paths[i]) < max_path_length:
        paths[i].append([0, 0])


X = []
new_paths = []


for i in range(number_of_maps):
    map_features = np.array(maps[i]).flatten()
    X.append(map_features)
    path_features = np.array(paths[i]).flatten()
    new_paths.append(path_features)

y = []
for i in new_paths:
    string_number = ''.join(map(str, i))
    decimal_number = int(string_number, 2)
    y.append(decimal_number)

print("Первая карта:")
for row in maps[0]:
    print(row)
print("Путь к цели:", paths[0])


X = np.array(X)
y = np.array(y)

print(X.shape)
print(y.shape)

Первая карта:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Путь к цели: [[1, 1], [1, 0], [1, 1], [1, 0], [1, 1], [1, 0], [1, 1], [1, 0], [1, 1], [1, 0], [1, 1], [1, 0], [0, 0], [0, 0], [0, 0]]
(2500, 225)
(2500,)


In [185]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model = svm.SVC(kernel='rbf', gamma='scale')
model.fit(X_train, y_train)

print("Первая карта:")
print(X_test[0].reshape(15, 15))

y_pred = model.predict(X_test[0].reshape(1, -1))

print("Путь к цели:")
n = str(format(y_pred[0], '0{}b'.format(30)))
for i in range(0, len(n), 2):
    pair = n[i:i+2]
    if pair == '00':
        print("Назад")
    elif pair == '11':
        print("Вперед")
    elif pair == '10':
        print("Налево")
    elif pair == '01':
        print("Направо")

Первая карта:
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Путь к цели:
Налево
Налево
Налево
Налево
Назад
Назад
Назад
Назад
Назад
Назад
Назад
Назад
Назад
Назад
Назад
